# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "warden:ancient_warden"
data modify storage animated_java:temp entry.data.rig_hash set value "74aa773ca758a7bd9d9f5b5d4c71c9c395dab6d78568bfcbab63878d5ae79fbf"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=warden.ancient_warden.node.right_tendril] run function warden:ancient_warden/zzz/summon/as_node/right_tendril
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.right_tendril set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.left_tendril] run function warden:ancient_warden/zzz/summon/as_node/left_tendril
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.left_tendril set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.head] run function warden:ancient_warden/zzz/summon/as_node/head
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.head set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.right_arm] run function warden:ancient_warden/zzz/summon/as_node/right_arm
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.right_arm set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.left_arm] run function warden:ancient_warden/zzz/summon/as_node/left_arm
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.left_arm set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.body1] run function warden:ancient_warden/zzz/summon/as_node/body1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.body1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.right_leg] run function warden:ancient_warden/zzz/summon/as_node/right_leg
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.right_leg set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.left_leg] run function warden:ancient_warden/zzz/summon/as_node/left_leg
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.left_leg set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line90] run function warden:ancient_warden/zzz/summon/as_node/line90
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line90 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line0] run function warden:ancient_warden/zzz/summon/as_node/line0
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line0 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line1] run function warden:ancient_warden/zzz/summon/as_node/line1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line2] run function warden:ancient_warden/zzz/summon/as_node/line2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve25] run function warden:ancient_warden/zzz/summon/as_node/curve25
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve25 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve26] run function warden:ancient_warden/zzz/summon/as_node/curve26
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve26 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve24] run function warden:ancient_warden/zzz/summon/as_node/curve24
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve24 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve23] run function warden:ancient_warden/zzz/summon/as_node/curve23
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve23 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve2] run function warden:ancient_warden/zzz/summon/as_node/curve2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve3] run function warden:ancient_warden/zzz/summon/as_node/curve3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve4] run function warden:ancient_warden/zzz/summon/as_node/curve4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve5] run function warden:ancient_warden/zzz/summon/as_node/curve5
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve5 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve6] run function warden:ancient_warden/zzz/summon/as_node/curve6
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve6 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve8] run function warden:ancient_warden/zzz/summon/as_node/curve8
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve8 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve10] run function warden:ancient_warden/zzz/summon/as_node/curve10
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve10 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve11] run function warden:ancient_warden/zzz/summon/as_node/curve11
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve11 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve13] run function warden:ancient_warden/zzz/summon/as_node/curve13
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve13 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve14] run function warden:ancient_warden/zzz/summon/as_node/curve14
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve14 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve15] run function warden:ancient_warden/zzz/summon/as_node/curve15
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve15 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve16] run function warden:ancient_warden/zzz/summon/as_node/curve16
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve16 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve19] run function warden:ancient_warden/zzz/summon/as_node/curve19
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve19 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve20] run function warden:ancient_warden/zzz/summon/as_node/curve20
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve20 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve21] run function warden:ancient_warden/zzz/summon/as_node/curve21
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve21 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve22] run function warden:ancient_warden/zzz/summon/as_node/curve22
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve22 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve27] run function warden:ancient_warden/zzz/summon/as_node/curve27
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve27 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve28] run function warden:ancient_warden/zzz/summon/as_node/curve28
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve28 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve29] run function warden:ancient_warden/zzz/summon/as_node/curve29
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve29 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve30] run function warden:ancient_warden/zzz/summon/as_node/curve30
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve30 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve31] run function warden:ancient_warden/zzz/summon/as_node/curve31
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve31 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve32] run function warden:ancient_warden/zzz/summon/as_node/curve32
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve32 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve33] run function warden:ancient_warden/zzz/summon/as_node/curve33
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve33 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve34] run function warden:ancient_warden/zzz/summon/as_node/curve34
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve34 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve35] run function warden:ancient_warden/zzz/summon/as_node/curve35
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve35 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve36] run function warden:ancient_warden/zzz/summon/as_node/curve36
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve36 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve37] run function warden:ancient_warden/zzz/summon/as_node/curve37
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve37 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve38] run function warden:ancient_warden/zzz/summon/as_node/curve38
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve38 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve39] run function warden:ancient_warden/zzz/summon/as_node/curve39
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve39 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve40] run function warden:ancient_warden/zzz/summon/as_node/curve40
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve40 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve41] run function warden:ancient_warden/zzz/summon/as_node/curve41
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve41 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve42] run function warden:ancient_warden/zzz/summon/as_node/curve42
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve42 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve43] run function warden:ancient_warden/zzz/summon/as_node/curve43
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve43 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve44] run function warden:ancient_warden/zzz/summon/as_node/curve44
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve44 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve45] run function warden:ancient_warden/zzz/summon/as_node/curve45
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve45 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve46] run function warden:ancient_warden/zzz/summon/as_node/curve46
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve46 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve47] run function warden:ancient_warden/zzz/summon/as_node/curve47
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve47 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve48] run function warden:ancient_warden/zzz/summon/as_node/curve48
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve48 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve49] run function warden:ancient_warden/zzz/summon/as_node/curve49
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve49 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve50] run function warden:ancient_warden/zzz/summon/as_node/curve50
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve50 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve51] run function warden:ancient_warden/zzz/summon/as_node/curve51
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve51 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve52] run function warden:ancient_warden/zzz/summon/as_node/curve52
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve52 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve53] run function warden:ancient_warden/zzz/summon/as_node/curve53
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve53 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve0] run function warden:ancient_warden/zzz/summon/as_node/curve0
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve0 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.ring] run function warden:ancient_warden/zzz/summon/as_node/ring
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ring set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line91] run function warden:ancient_warden/zzz/summon/as_node/line91
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line91 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line3] run function warden:ancient_warden/zzz/summon/as_node/line3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line4] run function warden:ancient_warden/zzz/summon/as_node/line4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line5] run function warden:ancient_warden/zzz/summon/as_node/line5
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line5 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve55] run function warden:ancient_warden/zzz/summon/as_node/curve55
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve55 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve56] run function warden:ancient_warden/zzz/summon/as_node/curve56
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve56 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve57] run function warden:ancient_warden/zzz/summon/as_node/curve57
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve57 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve59] run function warden:ancient_warden/zzz/summon/as_node/curve59
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve59 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve60] run function warden:ancient_warden/zzz/summon/as_node/curve60
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve60 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve61] run function warden:ancient_warden/zzz/summon/as_node/curve61
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve61 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve62] run function warden:ancient_warden/zzz/summon/as_node/curve62
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve62 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve63] run function warden:ancient_warden/zzz/summon/as_node/curve63
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve63 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve64] run function warden:ancient_warden/zzz/summon/as_node/curve64
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve64 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve66] run function warden:ancient_warden/zzz/summon/as_node/curve66
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve66 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve68] run function warden:ancient_warden/zzz/summon/as_node/curve68
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve68 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve69] run function warden:ancient_warden/zzz/summon/as_node/curve69
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve69 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve71] run function warden:ancient_warden/zzz/summon/as_node/curve71
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve71 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve72] run function warden:ancient_warden/zzz/summon/as_node/curve72
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve72 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve73] run function warden:ancient_warden/zzz/summon/as_node/curve73
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve73 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve74] run function warden:ancient_warden/zzz/summon/as_node/curve74
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve74 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve77] run function warden:ancient_warden/zzz/summon/as_node/curve77
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve77 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve78] run function warden:ancient_warden/zzz/summon/as_node/curve78
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve78 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve79] run function warden:ancient_warden/zzz/summon/as_node/curve79
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve79 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve80] run function warden:ancient_warden/zzz/summon/as_node/curve80
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve80 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve81] run function warden:ancient_warden/zzz/summon/as_node/curve81
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve81 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve82] run function warden:ancient_warden/zzz/summon/as_node/curve82
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve82 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve83] run function warden:ancient_warden/zzz/summon/as_node/curve83
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve83 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve84] run function warden:ancient_warden/zzz/summon/as_node/curve84
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve84 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve85] run function warden:ancient_warden/zzz/summon/as_node/curve85
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve85 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve86] run function warden:ancient_warden/zzz/summon/as_node/curve86
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve86 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve87] run function warden:ancient_warden/zzz/summon/as_node/curve87
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve87 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve88] run function warden:ancient_warden/zzz/summon/as_node/curve88
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve88 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve89] run function warden:ancient_warden/zzz/summon/as_node/curve89
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve89 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve90] run function warden:ancient_warden/zzz/summon/as_node/curve90
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve90 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve91] run function warden:ancient_warden/zzz/summon/as_node/curve91
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve91 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve92] run function warden:ancient_warden/zzz/summon/as_node/curve92
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve92 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve93] run function warden:ancient_warden/zzz/summon/as_node/curve93
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve93 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve94] run function warden:ancient_warden/zzz/summon/as_node/curve94
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve94 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve95] run function warden:ancient_warden/zzz/summon/as_node/curve95
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve95 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve96] run function warden:ancient_warden/zzz/summon/as_node/curve96
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve96 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve97] run function warden:ancient_warden/zzz/summon/as_node/curve97
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve97 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve98] run function warden:ancient_warden/zzz/summon/as_node/curve98
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve98 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve99] run function warden:ancient_warden/zzz/summon/as_node/curve99
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve99 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve100] run function warden:ancient_warden/zzz/summon/as_node/curve100
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve100 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve101] run function warden:ancient_warden/zzz/summon/as_node/curve101
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve101 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve102] run function warden:ancient_warden/zzz/summon/as_node/curve102
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve102 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve103] run function warden:ancient_warden/zzz/summon/as_node/curve103
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve103 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve104] run function warden:ancient_warden/zzz/summon/as_node/curve104
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve104 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve105] run function warden:ancient_warden/zzz/summon/as_node/curve105
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve105 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve106] run function warden:ancient_warden/zzz/summon/as_node/curve106
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve106 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve107] run function warden:ancient_warden/zzz/summon/as_node/curve107
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve107 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve54] run function warden:ancient_warden/zzz/summon/as_node/curve54
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve54 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.ring1] run function warden:ancient_warden/zzz/summon/as_node/ring1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ring1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line92] run function warden:ancient_warden/zzz/summon/as_node/line92
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line92 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line6] run function warden:ancient_warden/zzz/summon/as_node/line6
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line6 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line7] run function warden:ancient_warden/zzz/summon/as_node/line7
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line7 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line8] run function warden:ancient_warden/zzz/summon/as_node/line8
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line8 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve109] run function warden:ancient_warden/zzz/summon/as_node/curve109
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve109 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve110] run function warden:ancient_warden/zzz/summon/as_node/curve110
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve110 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve111] run function warden:ancient_warden/zzz/summon/as_node/curve111
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve111 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve113] run function warden:ancient_warden/zzz/summon/as_node/curve113
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve113 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve114] run function warden:ancient_warden/zzz/summon/as_node/curve114
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve114 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve115] run function warden:ancient_warden/zzz/summon/as_node/curve115
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve115 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve116] run function warden:ancient_warden/zzz/summon/as_node/curve116
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve116 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve117] run function warden:ancient_warden/zzz/summon/as_node/curve117
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve117 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve118] run function warden:ancient_warden/zzz/summon/as_node/curve118
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve118 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve120] run function warden:ancient_warden/zzz/summon/as_node/curve120
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve120 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve122] run function warden:ancient_warden/zzz/summon/as_node/curve122
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve122 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve123] run function warden:ancient_warden/zzz/summon/as_node/curve123
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve123 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve125] run function warden:ancient_warden/zzz/summon/as_node/curve125
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve125 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve126] run function warden:ancient_warden/zzz/summon/as_node/curve126
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve126 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve127] run function warden:ancient_warden/zzz/summon/as_node/curve127
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve127 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve128] run function warden:ancient_warden/zzz/summon/as_node/curve128
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve128 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve131] run function warden:ancient_warden/zzz/summon/as_node/curve131
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve131 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve132] run function warden:ancient_warden/zzz/summon/as_node/curve132
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve132 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve133] run function warden:ancient_warden/zzz/summon/as_node/curve133
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve133 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve134] run function warden:ancient_warden/zzz/summon/as_node/curve134
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve134 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve135] run function warden:ancient_warden/zzz/summon/as_node/curve135
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve135 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve136] run function warden:ancient_warden/zzz/summon/as_node/curve136
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve136 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve137] run function warden:ancient_warden/zzz/summon/as_node/curve137
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve137 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve138] run function warden:ancient_warden/zzz/summon/as_node/curve138
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve138 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve139] run function warden:ancient_warden/zzz/summon/as_node/curve139
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve139 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve140] run function warden:ancient_warden/zzz/summon/as_node/curve140
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve140 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve141] run function warden:ancient_warden/zzz/summon/as_node/curve141
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve141 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve142] run function warden:ancient_warden/zzz/summon/as_node/curve142
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve142 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve143] run function warden:ancient_warden/zzz/summon/as_node/curve143
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve143 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve144] run function warden:ancient_warden/zzz/summon/as_node/curve144
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve144 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve145] run function warden:ancient_warden/zzz/summon/as_node/curve145
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve145 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve146] run function warden:ancient_warden/zzz/summon/as_node/curve146
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve146 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve147] run function warden:ancient_warden/zzz/summon/as_node/curve147
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve147 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve148] run function warden:ancient_warden/zzz/summon/as_node/curve148
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve148 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve149] run function warden:ancient_warden/zzz/summon/as_node/curve149
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve149 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve150] run function warden:ancient_warden/zzz/summon/as_node/curve150
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve150 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve151] run function warden:ancient_warden/zzz/summon/as_node/curve151
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve151 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve152] run function warden:ancient_warden/zzz/summon/as_node/curve152
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve152 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve153] run function warden:ancient_warden/zzz/summon/as_node/curve153
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve153 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve154] run function warden:ancient_warden/zzz/summon/as_node/curve154
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve154 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve155] run function warden:ancient_warden/zzz/summon/as_node/curve155
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve155 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve156] run function warden:ancient_warden/zzz/summon/as_node/curve156
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve156 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve157] run function warden:ancient_warden/zzz/summon/as_node/curve157
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve157 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve158] run function warden:ancient_warden/zzz/summon/as_node/curve158
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve158 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve159] run function warden:ancient_warden/zzz/summon/as_node/curve159
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve159 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve160] run function warden:ancient_warden/zzz/summon/as_node/curve160
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve160 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve161] run function warden:ancient_warden/zzz/summon/as_node/curve161
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve161 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve108] run function warden:ancient_warden/zzz/summon/as_node/curve108
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve108 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.ring2] run function warden:ancient_warden/zzz/summon/as_node/ring2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ring2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line93] run function warden:ancient_warden/zzz/summon/as_node/line93
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line93 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line9] run function warden:ancient_warden/zzz/summon/as_node/line9
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line9 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line10] run function warden:ancient_warden/zzz/summon/as_node/line10
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line10 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line11] run function warden:ancient_warden/zzz/summon/as_node/line11
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line11 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve163] run function warden:ancient_warden/zzz/summon/as_node/curve163
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve163 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve164] run function warden:ancient_warden/zzz/summon/as_node/curve164
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve164 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve165] run function warden:ancient_warden/zzz/summon/as_node/curve165
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve165 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve167] run function warden:ancient_warden/zzz/summon/as_node/curve167
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve167 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve168] run function warden:ancient_warden/zzz/summon/as_node/curve168
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve168 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve169] run function warden:ancient_warden/zzz/summon/as_node/curve169
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve169 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve170] run function warden:ancient_warden/zzz/summon/as_node/curve170
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve170 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve171] run function warden:ancient_warden/zzz/summon/as_node/curve171
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve171 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve172] run function warden:ancient_warden/zzz/summon/as_node/curve172
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve172 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve174] run function warden:ancient_warden/zzz/summon/as_node/curve174
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve174 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve176] run function warden:ancient_warden/zzz/summon/as_node/curve176
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve176 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve177] run function warden:ancient_warden/zzz/summon/as_node/curve177
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve177 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve179] run function warden:ancient_warden/zzz/summon/as_node/curve179
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve179 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve180] run function warden:ancient_warden/zzz/summon/as_node/curve180
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve180 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve181] run function warden:ancient_warden/zzz/summon/as_node/curve181
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve181 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve182] run function warden:ancient_warden/zzz/summon/as_node/curve182
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve182 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve185] run function warden:ancient_warden/zzz/summon/as_node/curve185
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve185 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve186] run function warden:ancient_warden/zzz/summon/as_node/curve186
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve186 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve187] run function warden:ancient_warden/zzz/summon/as_node/curve187
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve187 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve188] run function warden:ancient_warden/zzz/summon/as_node/curve188
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve188 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve189] run function warden:ancient_warden/zzz/summon/as_node/curve189
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve189 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve190] run function warden:ancient_warden/zzz/summon/as_node/curve190
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve190 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve191] run function warden:ancient_warden/zzz/summon/as_node/curve191
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve191 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve192] run function warden:ancient_warden/zzz/summon/as_node/curve192
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve192 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve193] run function warden:ancient_warden/zzz/summon/as_node/curve193
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve193 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve194] run function warden:ancient_warden/zzz/summon/as_node/curve194
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve194 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve195] run function warden:ancient_warden/zzz/summon/as_node/curve195
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve195 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve196] run function warden:ancient_warden/zzz/summon/as_node/curve196
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve196 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve197] run function warden:ancient_warden/zzz/summon/as_node/curve197
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve197 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve198] run function warden:ancient_warden/zzz/summon/as_node/curve198
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve198 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve199] run function warden:ancient_warden/zzz/summon/as_node/curve199
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve199 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve200] run function warden:ancient_warden/zzz/summon/as_node/curve200
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve200 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve201] run function warden:ancient_warden/zzz/summon/as_node/curve201
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve201 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve202] run function warden:ancient_warden/zzz/summon/as_node/curve202
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve202 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve203] run function warden:ancient_warden/zzz/summon/as_node/curve203
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve203 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve204] run function warden:ancient_warden/zzz/summon/as_node/curve204
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve204 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve205] run function warden:ancient_warden/zzz/summon/as_node/curve205
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve205 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve206] run function warden:ancient_warden/zzz/summon/as_node/curve206
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve206 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve207] run function warden:ancient_warden/zzz/summon/as_node/curve207
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve207 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve208] run function warden:ancient_warden/zzz/summon/as_node/curve208
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve208 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve209] run function warden:ancient_warden/zzz/summon/as_node/curve209
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve209 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve210] run function warden:ancient_warden/zzz/summon/as_node/curve210
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve210 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve211] run function warden:ancient_warden/zzz/summon/as_node/curve211
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve211 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve212] run function warden:ancient_warden/zzz/summon/as_node/curve212
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve212 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve213] run function warden:ancient_warden/zzz/summon/as_node/curve213
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve213 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve214] run function warden:ancient_warden/zzz/summon/as_node/curve214
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve214 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve215] run function warden:ancient_warden/zzz/summon/as_node/curve215
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve215 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve162] run function warden:ancient_warden/zzz/summon/as_node/curve162
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve162 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.ring3] run function warden:ancient_warden/zzz/summon/as_node/ring3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ring3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line94] run function warden:ancient_warden/zzz/summon/as_node/line94
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line94 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line12] run function warden:ancient_warden/zzz/summon/as_node/line12
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line12 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line13] run function warden:ancient_warden/zzz/summon/as_node/line13
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line13 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line14] run function warden:ancient_warden/zzz/summon/as_node/line14
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line14 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve217] run function warden:ancient_warden/zzz/summon/as_node/curve217
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve217 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve218] run function warden:ancient_warden/zzz/summon/as_node/curve218
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve218 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve219] run function warden:ancient_warden/zzz/summon/as_node/curve219
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve219 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve221] run function warden:ancient_warden/zzz/summon/as_node/curve221
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve221 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve222] run function warden:ancient_warden/zzz/summon/as_node/curve222
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve222 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve223] run function warden:ancient_warden/zzz/summon/as_node/curve223
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve223 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve224] run function warden:ancient_warden/zzz/summon/as_node/curve224
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve224 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve225] run function warden:ancient_warden/zzz/summon/as_node/curve225
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve225 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve226] run function warden:ancient_warden/zzz/summon/as_node/curve226
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve226 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve228] run function warden:ancient_warden/zzz/summon/as_node/curve228
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve228 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve230] run function warden:ancient_warden/zzz/summon/as_node/curve230
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve230 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve231] run function warden:ancient_warden/zzz/summon/as_node/curve231
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve231 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve233] run function warden:ancient_warden/zzz/summon/as_node/curve233
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve233 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve234] run function warden:ancient_warden/zzz/summon/as_node/curve234
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve234 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve235] run function warden:ancient_warden/zzz/summon/as_node/curve235
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve235 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve236] run function warden:ancient_warden/zzz/summon/as_node/curve236
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve236 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve239] run function warden:ancient_warden/zzz/summon/as_node/curve239
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve239 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve240] run function warden:ancient_warden/zzz/summon/as_node/curve240
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve240 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve241] run function warden:ancient_warden/zzz/summon/as_node/curve241
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve241 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve242] run function warden:ancient_warden/zzz/summon/as_node/curve242
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve242 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve243] run function warden:ancient_warden/zzz/summon/as_node/curve243
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve243 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve244] run function warden:ancient_warden/zzz/summon/as_node/curve244
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve244 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve245] run function warden:ancient_warden/zzz/summon/as_node/curve245
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve245 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve246] run function warden:ancient_warden/zzz/summon/as_node/curve246
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve246 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve247] run function warden:ancient_warden/zzz/summon/as_node/curve247
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve247 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve248] run function warden:ancient_warden/zzz/summon/as_node/curve248
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve248 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve249] run function warden:ancient_warden/zzz/summon/as_node/curve249
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve249 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve250] run function warden:ancient_warden/zzz/summon/as_node/curve250
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve250 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve251] run function warden:ancient_warden/zzz/summon/as_node/curve251
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve251 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve252] run function warden:ancient_warden/zzz/summon/as_node/curve252
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve252 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve253] run function warden:ancient_warden/zzz/summon/as_node/curve253
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve253 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve254] run function warden:ancient_warden/zzz/summon/as_node/curve254
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve254 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve255] run function warden:ancient_warden/zzz/summon/as_node/curve255
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve255 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve256] run function warden:ancient_warden/zzz/summon/as_node/curve256
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve256 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve257] run function warden:ancient_warden/zzz/summon/as_node/curve257
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve257 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve258] run function warden:ancient_warden/zzz/summon/as_node/curve258
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve258 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve259] run function warden:ancient_warden/zzz/summon/as_node/curve259
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve259 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve260] run function warden:ancient_warden/zzz/summon/as_node/curve260
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve260 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve261] run function warden:ancient_warden/zzz/summon/as_node/curve261
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve261 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve262] run function warden:ancient_warden/zzz/summon/as_node/curve262
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve262 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve263] run function warden:ancient_warden/zzz/summon/as_node/curve263
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve263 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve264] run function warden:ancient_warden/zzz/summon/as_node/curve264
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve264 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve265] run function warden:ancient_warden/zzz/summon/as_node/curve265
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve265 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve266] run function warden:ancient_warden/zzz/summon/as_node/curve266
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve266 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve267] run function warden:ancient_warden/zzz/summon/as_node/curve267
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve267 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve268] run function warden:ancient_warden/zzz/summon/as_node/curve268
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve268 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve269] run function warden:ancient_warden/zzz/summon/as_node/curve269
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve269 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve216] run function warden:ancient_warden/zzz/summon/as_node/curve216
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve216 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.ring4] run function warden:ancient_warden/zzz/summon/as_node/ring4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ring4 set from storage animated_java:gu out
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function warden:ancient_warden/zzz/set_default_pose
execute if data storage animated_java:temp args.variant run function warden:ancient_warden/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function warden:ancient_warden/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s remove aj.new
execute on passengers run tag @s remove aj.new