# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "warden:ancient_warden"
data modify storage animated_java:temp entry.data.rig_hash set value "2ab7fad8ef4ac9289f5ff5272fc15b717e466e34915adbd2b2af55684764e482"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=warden.ancient_warden.node.right_tendril] run function warden:ancient_warden/zzz/summon/as_node/right_tendril
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.right_tendril set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.left_tendril] run function warden:ancient_warden/zzz/summon/as_node/left_tendril
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.left_tendril set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.head] run function warden:ancient_warden/zzz/summon/as_node/head
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.head set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.right_arm] run function warden:ancient_warden/zzz/summon/as_node/right_arm
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.right_arm set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.left_arm] run function warden:ancient_warden/zzz/summon/as_node/left_arm
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.left_arm set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.body1] run function warden:ancient_warden/zzz/summon/as_node/body1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.body1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.right_leg] run function warden:ancient_warden/zzz/summon/as_node/right_leg
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.right_leg set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.left_leg] run function warden:ancient_warden/zzz/summon/as_node/left_leg
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.left_leg set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.hexadecagon] run function warden:ancient_warden/zzz/summon/as_node/hexadecagon
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.hexadecagon set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line90] run function warden:ancient_warden/zzz/summon/as_node/line90
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line90 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line0] run function warden:ancient_warden/zzz/summon/as_node/line0
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line0 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line1] run function warden:ancient_warden/zzz/summon/as_node/line1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line2] run function warden:ancient_warden/zzz/summon/as_node/line2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.ring] run function warden:ancient_warden/zzz/summon/as_node/ring
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ring set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.hexadecagon1] run function warden:ancient_warden/zzz/summon/as_node/hexadecagon1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.hexadecagon1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line91] run function warden:ancient_warden/zzz/summon/as_node/line91
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line91 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line3] run function warden:ancient_warden/zzz/summon/as_node/line3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line4] run function warden:ancient_warden/zzz/summon/as_node/line4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line5] run function warden:ancient_warden/zzz/summon/as_node/line5
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line5 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.ring1] run function warden:ancient_warden/zzz/summon/as_node/ring1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ring1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line92] run function warden:ancient_warden/zzz/summon/as_node/line92
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line92 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line6] run function warden:ancient_warden/zzz/summon/as_node/line6
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line6 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line7] run function warden:ancient_warden/zzz/summon/as_node/line7
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line7 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line8] run function warden:ancient_warden/zzz/summon/as_node/line8
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line8 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.hexadecagon2] run function warden:ancient_warden/zzz/summon/as_node/hexadecagon2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.hexadecagon2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.ring2] run function warden:ancient_warden/zzz/summon/as_node/ring2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ring2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line93] run function warden:ancient_warden/zzz/summon/as_node/line93
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line93 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line9] run function warden:ancient_warden/zzz/summon/as_node/line9
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line9 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line10] run function warden:ancient_warden/zzz/summon/as_node/line10
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line10 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line11] run function warden:ancient_warden/zzz/summon/as_node/line11
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line11 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.hexadecagon3] run function warden:ancient_warden/zzz/summon/as_node/hexadecagon3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.hexadecagon3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.ring3] run function warden:ancient_warden/zzz/summon/as_node/ring3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ring3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line94] run function warden:ancient_warden/zzz/summon/as_node/line94
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line94 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line12] run function warden:ancient_warden/zzz/summon/as_node/line12
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line12 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line13] run function warden:ancient_warden/zzz/summon/as_node/line13
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line13 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line14] run function warden:ancient_warden/zzz/summon/as_node/line14
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line14 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.hexadecagon4] run function warden:ancient_warden/zzz/summon/as_node/hexadecagon4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.hexadecagon4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.ring4] run function warden:ancient_warden/zzz/summon/as_node/ring4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ring4 set from storage animated_java:gu out
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function warden:ancient_warden/zzz/set_default_pose
execute if data storage animated_java:temp args.variant run function warden:ancient_warden/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function warden:ancient_warden/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s remove aj.new
execute on passengers run tag @s remove aj.new