# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "warden:ancient_warden"
data modify storage animated_java:temp entry.data.rig_hash set value "09d56f93ab646f44cde2a180e27627ea1d8a8d169d786acba85b43c1ce581bee"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=warden.ancient_warden.node.right_ribcage] run function warden:ancient_warden/zzz/summon/as_node/right_ribcage
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.right_ribcage set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.left_ribcage] run function warden:ancient_warden/zzz/summon/as_node/left_ribcage
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.left_ribcage set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.right_tendril] run function warden:ancient_warden/zzz/summon/as_node/right_tendril
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.right_tendril set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.left_tendril] run function warden:ancient_warden/zzz/summon/as_node/left_tendril
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.left_tendril set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.head] run function warden:ancient_warden/zzz/summon/as_node/head
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.head set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.right_arm] run function warden:ancient_warden/zzz/summon/as_node/right_arm
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.right_arm set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.left_arm] run function warden:ancient_warden/zzz/summon/as_node/left_arm
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.left_arm set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.body] run function warden:ancient_warden/zzz/summon/as_node/body
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.body set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.right_leg] run function warden:ancient_warden/zzz/summon/as_node/right_leg
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.right_leg set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.left_leg] run function warden:ancient_warden/zzz/summon/as_node/left_leg
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.left_leg set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line90] run function warden:ancient_warden/zzz/summon/as_node/line90
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line90 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line0] run function warden:ancient_warden/zzz/summon/as_node/line0
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line0 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line1] run function warden:ancient_warden/zzz/summon/as_node/line1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.line2] run function warden:ancient_warden/zzz/summon/as_node/line2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve25] run function warden:ancient_warden/zzz/summon/as_node/curve25
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve25 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve26] run function warden:ancient_warden/zzz/summon/as_node/curve26
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve26 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve24] run function warden:ancient_warden/zzz/summon/as_node/curve24
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve24 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve23] run function warden:ancient_warden/zzz/summon/as_node/curve23
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve23 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve2] run function warden:ancient_warden/zzz/summon/as_node/curve2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve3] run function warden:ancient_warden/zzz/summon/as_node/curve3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve4] run function warden:ancient_warden/zzz/summon/as_node/curve4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve5] run function warden:ancient_warden/zzz/summon/as_node/curve5
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve5 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve6] run function warden:ancient_warden/zzz/summon/as_node/curve6
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve6 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve8] run function warden:ancient_warden/zzz/summon/as_node/curve8
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve8 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve10] run function warden:ancient_warden/zzz/summon/as_node/curve10
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve10 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve11] run function warden:ancient_warden/zzz/summon/as_node/curve11
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve11 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve13] run function warden:ancient_warden/zzz/summon/as_node/curve13
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve13 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve14] run function warden:ancient_warden/zzz/summon/as_node/curve14
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve14 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve15] run function warden:ancient_warden/zzz/summon/as_node/curve15
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve15 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve16] run function warden:ancient_warden/zzz/summon/as_node/curve16
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve16 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve19] run function warden:ancient_warden/zzz/summon/as_node/curve19
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve19 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve20] run function warden:ancient_warden/zzz/summon/as_node/curve20
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve20 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve21] run function warden:ancient_warden/zzz/summon/as_node/curve21
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve21 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve22] run function warden:ancient_warden/zzz/summon/as_node/curve22
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve22 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve27] run function warden:ancient_warden/zzz/summon/as_node/curve27
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve27 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve28] run function warden:ancient_warden/zzz/summon/as_node/curve28
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve28 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve29] run function warden:ancient_warden/zzz/summon/as_node/curve29
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve29 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve30] run function warden:ancient_warden/zzz/summon/as_node/curve30
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve30 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve31] run function warden:ancient_warden/zzz/summon/as_node/curve31
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve31 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve32] run function warden:ancient_warden/zzz/summon/as_node/curve32
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve32 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve33] run function warden:ancient_warden/zzz/summon/as_node/curve33
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve33 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve34] run function warden:ancient_warden/zzz/summon/as_node/curve34
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve34 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve35] run function warden:ancient_warden/zzz/summon/as_node/curve35
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve35 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve36] run function warden:ancient_warden/zzz/summon/as_node/curve36
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve36 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve37] run function warden:ancient_warden/zzz/summon/as_node/curve37
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve37 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve38] run function warden:ancient_warden/zzz/summon/as_node/curve38
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve38 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve39] run function warden:ancient_warden/zzz/summon/as_node/curve39
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve39 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve40] run function warden:ancient_warden/zzz/summon/as_node/curve40
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve40 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve41] run function warden:ancient_warden/zzz/summon/as_node/curve41
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve41 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve42] run function warden:ancient_warden/zzz/summon/as_node/curve42
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve42 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve43] run function warden:ancient_warden/zzz/summon/as_node/curve43
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve43 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve44] run function warden:ancient_warden/zzz/summon/as_node/curve44
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve44 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve45] run function warden:ancient_warden/zzz/summon/as_node/curve45
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve45 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve46] run function warden:ancient_warden/zzz/summon/as_node/curve46
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve46 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve47] run function warden:ancient_warden/zzz/summon/as_node/curve47
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve47 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve48] run function warden:ancient_warden/zzz/summon/as_node/curve48
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve48 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve49] run function warden:ancient_warden/zzz/summon/as_node/curve49
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve49 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve50] run function warden:ancient_warden/zzz/summon/as_node/curve50
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve50 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve51] run function warden:ancient_warden/zzz/summon/as_node/curve51
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve51 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve52] run function warden:ancient_warden/zzz/summon/as_node/curve52
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve52 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve53] run function warden:ancient_warden/zzz/summon/as_node/curve53
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve53 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.curve0] run function warden:ancient_warden/zzz/summon/as_node/curve0
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.curve0 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_warden.node.ring] run function warden:ancient_warden/zzz/summon/as_node/ring
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ring set from storage animated_java:gu out
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function warden:ancient_warden/zzz/set_default_pose
execute if data storage animated_java:temp args.variant run function warden:ancient_warden/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function warden:ancient_warden/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s remove aj.new
execute on passengers run tag @s remove aj.new