# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "warden:ancient_ring"
data modify storage animated_java:temp entry.data.rig_hash set value "f2330f849333e48f200dd45e10a5bd419111d11d49361ddec343257ab8f28487"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=warden.ancient_ring.node.hexadecagon] run function warden:ancient_ring/zzz/summon/as_node/hexadecagon
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.hexadecagon set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_ring.node.line90] run function warden:ancient_ring/zzz/summon/as_node/line90
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line90 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_ring.node.line0] run function warden:ancient_ring/zzz/summon/as_node/line0
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line0 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_ring.node.line1] run function warden:ancient_ring/zzz/summon/as_node/line1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_ring.node.line2] run function warden:ancient_ring/zzz/summon/as_node/line2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=warden.ancient_ring.node.ring] run function warden:ancient_ring/zzz/summon/as_node/ring
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ring set from storage animated_java:gu out
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function warden:ancient_ring/zzz/set_default_pose
execute if data storage animated_java:temp args.variant run function warden:ancient_ring/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function warden:ancient_ring/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s remove aj.new
execute on passengers run tag @s remove aj.new