# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [-4f,0f,0f,0f,0f,4f,0f,2.0625f,0f,0f,-4f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [0f,0f,-4f,-0.0105f,0f,4f,0f,0.325f,4f,0f,0f,0.2541f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-4f,0f,0f,-0.0041f,0f,4f,0f,0.325f,0f,0f,-4f,0.2479f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-2.8284f,0f,-2.8284f,-0.0044f,0f,4f,0f,0.325f,2.8284f,0f,-2.8284f,0.2514f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-2.8284f,0f,2.8284f,-0.0014f,0f,4f,0f,0.325f,-2.8284f,0f,-2.8284f,0.2456f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-9.5833f,0f,0f,0f,0f,9.5833f,0f,-13.75f,0f,0f,-9.5833f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}