# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [1.2361f,0f,-3.8042f,0.2378f,0f,4f,0f,2.0625f,3.8042f,0f,1.2361f,-0.0773f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [3.8042f,0f,1.2361f,0.2449f,0f,4f,0f,0.325f,-1.2361f,0f,3.8042f,-0.0686f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [1.2361f,0f,-3.8042f,0.237f,0f,4f,0f,0.325f,3.8042f,0f,1.2361f,-0.0727f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [3.564f,0f,-1.816f,0.2404f,0f,4f,0f,0.325f,1.816f,0f,3.564f,-0.0735f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-1.816f,0f,-3.564f,0.234f,0f,4f,0f,0.325f,3.564f,0f,-1.816f,-0.0746f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [2.9614f,0f,-9.1143f,0f,0f,9.5833f,0f,-13.75f,9.1143f,0f,2.9614f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}