# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [-2.3511f,0f,-3.2361f,0.2023f,0f,4f,0f,2.0625f,3.2361f,0f,-2.3511f,0.1469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [3.2361f,0f,-2.3511f,0.1994f,0f,4f,0f,0.325f,2.3511f,0f,3.2361f,0.1578f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-2.3511f,0f,-3.2361f,0.1981f,0f,4f,0f,0.325f,3.2361f,0f,-2.3511f,0.149f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [0.6257f,0f,-3.9508f,0.2008f,0f,4f,0f,0.325f,3.9508f,0f,0.6257f,0.1513f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-3.9508f,0f,-0.6257f,0.1979f,0f,4f,0f,0.325f,0.6257f,0f,-3.9508f,0.1455f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-5.6329f,0f,-7.7531f,0f,0f,9.5833f,0f,-13.75f,7.7531f,0f,-5.6329f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}