# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [-3.564f,0f,-1.816f,0.1135f,0f,4f,0f,2.0625f,1.816f,0f,-3.564f,0.2228f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [1.816f,0f,-3.564f,0.106f,0f,4f,0f,0.325f,3.564f,0f,1.816f,0.2311f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-3.564f,0f,-1.816f,0.1089f,0f,4f,0f,0.325f,1.816f,0f,-3.564f,0.2227f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-1.2361f,0f,-3.8042f,0.1102f,0f,4f,0f,0.325f,3.8042f,0f,-1.2361f,0.226f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-3.8042f,0f,1.2361f,0.1103f,0f,4f,0f,0.325f,-1.2361f,0f,-3.8042f,0.2195f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-8.5388f,0f,-4.3507f,0f,0f,9.5833f,0f,-13.75f,4.3507f,0f,-8.5388f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}