# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage warden:ancient_ring rig_hash set value 'a86d18d6f2496d5016b6cfd3176c4dba91f57e027d4301a73945a3cc2f083896'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.small_to_big.frame dummy
scoreboard objectives add aj.big_to_small.frame dummy
scoreboard objectives add aj.idle2.frame dummy