# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage warden:ancient_ring rig_hash set value 'cbc405f004a4843e0e082e905218ab39fd986b92bf6aa7b01e562f102e2289de'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.start_phase1.frame dummy
scoreboard objectives add aj.idle2.frame dummy