# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage warden:ancient_ring rig_hash set value 'f2330f849333e48f200dd45e10a5bd419111d11d49361ddec343257ab8f28487'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.small_to_big.frame dummy
scoreboard objectives add aj.big_to_small.frame dummy
scoreboard objectives add aj.idle2.frame dummy