# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players set @s aj.shield_attack_start.frame 0
tag @s add aj.transforms_only
execute at @s run function warden:ancient_warden/animations/shield_attack_start/zzz/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only
tag @s remove warden.ancient_warden.animation.shield_attack_start.playing