# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0.9975f,0f,2.8731f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0.9975f,0f,2.8731f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.9975f,0f,2.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [-1.1556f,0f,0.183f,-0.0114f,0f,1f,0f,3.9938f,-0.183f,0f,-1.1556f,0.0597f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-0.183f,0f,-1.1556f,-0.0146f,0f,1f,0f,3.5438f,1.1556f,0f,-0.183f,0.0604f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-1.1556f,0f,0.183f,-0.0125f,0f,1f,0f,3.5438f,-0.183f,0f,-1.1556f,0.0589f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-0.9465f,0f,-0.6877f,-0.0128f,0f,1f,0f,3.5438f,0.6877f,0f,-0.9465f,0.0599f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-0.6877f,0f,0.9465f,-0.0116f,0f,1f,0f,3.5438f,-0.9465f,0f,-0.6877f,0.0584f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-2.7686f,0f,0.4385f,0f,0f,2.3958f,0f,0.025f,-0.4385f,0f,-2.7686f,-0.0125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}