# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [-1f,0f,0.0079f,-0.0005f,0f,1f,0f,3.9688f,-0.0079f,0f,-1f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-0.0079f,0f,-1f,-0.0031f,0f,1f,0f,3.5188f,1f,0f,-0.0079f,0.0635f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-1f,0f,0.0079f,-0.0015f,0f,1f,0f,3.5188f,-0.0079f,0f,-1f,0.062f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-0.7127f,0f,-0.7015f,-0.0016f,0f,1f,0f,3.5188f,0.7015f,0f,-0.7127f,0.0628f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-0.7015f,0f,0.7127f,-0.0008f,0f,1f,0f,3.5188f,-0.7127f,0f,-0.7015f,0.0614f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-2.3958f,0f,0.019f,0f,0f,2.3958f,0f,0f,-0.019f,0f,-2.3958f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}