# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [-0.7015f,0f,0.7127f,-0.0445f,0f,1f,0f,3.9688f,-0.7127f,0f,-0.7015f,0.0438f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-0.7127f,0f,-0.7015f,-0.0471f,0f,1f,0f,3.5188f,0.7015f,0f,-0.7127f,0.0427f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-0.7015f,0f,0.7127f,-0.0449f,0f,1f,0f,3.5188f,-0.7127f,0f,-0.7015f,0.0427f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-1f,0f,0.0079f,-0.0456f,0f,1f,0f,3.5188f,-0.0079f,0f,-1f,0.0433f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [0.0079f,0f,1f,-0.044f,0f,1f,0f,3.5188f,-1f,0f,0.0079f,0.0428f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-1.6806f,0f,1.7075f,0f,0f,2.3958f,0f,0f,-1.7075f,0f,-1.6806f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}