# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0.9725f,0f,2.8544f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0.9725f,0f,2.8544f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.9725f,0f,2.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [0.4224f,0f,2.6668f,-0.1667f,0f,1f,0f,4.1146f,-2.6668f,0f,0.4224f,-0.1514f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-2.6668f,0f,0.4224f,-0.1683f,0f,1f,0f,3.6646f,-0.4224f,0f,-2.6668f,-0.1588f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [0.4224f,0f,2.6668f,-0.1648f,0f,1f,0f,3.6646f,-2.6668f,0f,0.4224f,-0.1539f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-1.587f,0f,2.1843f,-0.1671f,0f,1f,0f,3.6646f,-2.1843f,0f,-1.587f,-0.1545f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [2.1843f,0f,1.587f,-0.1636f,0f,1f,0f,3.6646f,-1.587f,0f,2.1843f,-0.1519f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [1.0119f,0f,6.3891f,0f,0f,2.3958f,0f,0.1458f,-6.3891f,0f,1.0119f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}