# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0.873f,0f,2.8161f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0.873f,0f,2.8161f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.97f,0f,2.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [0.8343f,0f,2.5679f,-0.1605f,0f,1f,0f,4.0104f,-2.5679f,0f,0.8343f,-0.1771f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-2.5679f,0f,0.8343f,-0.1609f,0f,1f,0f,3.5604f,-0.8343f,0f,-2.5679f,-0.1847f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [0.8343f,0f,2.5679f,-0.1583f,0f,1f,0f,3.5604f,-2.5679f,0f,0.8343f,-0.1793f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-1.2258f,0f,2.4057f,-0.1605f,0f,1f,0f,3.5604f,-2.4057f,0f,-1.2258f,-0.1802f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [2.4057f,0f,1.2258f,-0.1574f,0f,1f,0f,3.5604f,-1.2258f,0f,2.4057f,-0.1771f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [1.999f,0f,6.1521f,0f,0f,2.3958f,0f,0.0417f,-6.1521f,0f,1.999f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}