# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [-0.6494f,0f,0.7604f,-0.0475f,0f,1f,0f,3.9688f,-0.7604f,0f,-0.6494f,0.0406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-0.7604f,0f,-0.6494f,-0.05f,0f,1f,0f,3.5188f,0.6494f,0f,-0.7604f,0.0393f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-0.6494f,0f,0.7604f,-0.0478f,0f,1f,0f,3.5188f,-0.7604f,0f,-0.6494f,0.0395f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-0.9969f,0f,0.0785f,-0.0485f,0f,1f,0f,3.5188f,-0.0785f,0f,-0.9969f,0.04f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [0.0785f,0f,0.9969f,-0.0469f,0f,1f,0f,3.5188f,-0.9969f,0f,0.0785f,0.0396f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-1.556f,0f,1.8218f,0f,0f,2.3958f,0f,0f,-1.8218f,0f,-1.556f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}