# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0.774f,0f,2.7781f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0.774f,0f,2.7781f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.9675f,0f,2.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [1.2258f,0f,2.4057f,-0.1504f,0f,1f,0f,3.9063f,-2.4057f,0f,1.2258f,-0.2016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-2.4057f,0f,1.2258f,-0.1496f,0f,1f,0f,3.4563f,-1.2258f,0f,-2.4057f,-0.2091f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [1.2258f,0f,2.4057f,-0.1478f,0f,1f,0f,3.4563f,-2.4057f,0f,1.2258f,-0.2034f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-0.8343f,0f,2.5679f,-0.1498f,0f,1f,0f,3.4563f,-2.5679f,0f,-0.8343f,-0.2047f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [2.5679f,0f,0.8343f,-0.1473f,0f,1f,0f,3.4563f,-0.8343f,0f,2.5679f,-0.2011f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [2.9368f,0f,5.7637f,0f,0f,2.3958f,0f,-0.0625f,-5.7637f,0f,2.9368f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}