# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0.6755f,0f,2.7402f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0.6755f,0f,2.7402f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.965f,0f,2.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [1.587f,0f,2.1843f,-0.1365f,0f,1f,0f,3.8021f,-2.1843f,0f,1.587f,-0.2242f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-2.1843f,0f,1.587f,-0.1346f,0f,1f,0f,3.3521f,-1.587f,0f,-2.1843f,-0.2315f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [1.587f,0f,2.1843f,-0.1338f,0f,1f,0f,3.3521f,-2.1843f,0f,1.587f,-0.2256f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-0.4224f,0f,2.6668f,-0.1355f,0f,1f,0f,3.3521f,-2.6668f,0f,-0.4224f,-0.2271f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [2.6668f,0f,0.4224f,-0.1336f,0f,1f,0f,3.3521f,-0.4224f,0f,2.6668f,-0.2232f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [3.8022f,0f,5.2333f,0f,0f,2.3958f,0f,-0.1667f,-5.2333f,0f,3.8022f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}