# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0.5775f,0f,2.7025f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0.5775f,0f,2.7025f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.9625f,0f,2.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [1.9092f,0f,1.9092f,-0.1193f,0f,1f,0f,3.6979f,-1.9092f,0f,1.9092f,-0.2443f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-1.9092f,0f,1.9092f,-0.1163f,0f,1f,0f,3.2479f,-1.9092f,0f,-1.9092f,-0.2513f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [1.9092f,0f,1.9092f,-0.1164f,0f,1f,0f,3.2479f,-1.9092f,0f,1.9092f,-0.2453f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [0f,0f,2.7f,-0.1179f,0f,1f,0f,3.2479f,-2.7f,0f,0f,-0.2471f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [2.7f,0f,0f,-0.1166f,0f,1f,0f,3.2479f,0f,0f,2.7f,-0.2429f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [4.5741f,0f,4.5741f,0f,0f,2.3958f,0f,-0.2708f,-4.5741f,0f,4.5741f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}