# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0.224f,0f,2.489f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0.224f,0f,2.489f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.7467f,0f,2.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [2.5679f,0f,0.8343f,-0.0521f,0f,1f,0f,3.3854f,-0.8343f,0f,2.5679f,-0.2855f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-0.8343f,0f,2.5679f,-0.0463f,0f,1f,0f,2.9354f,-2.5679f,0f,-0.8343f,-0.2903f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [2.5679f,0f,0.8343f,-0.0491f,0f,1f,0f,2.9354f,-0.8343f,0f,2.5679f,-0.285f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [1.2258f,0f,2.4057f,-0.0496f,0f,1f,0f,2.9354f,-2.4057f,0f,1.2258f,-0.2873f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [2.4057f,0f,-1.2258f,-0.0503f,0f,1f,0f,2.9354f,1.2258f,0f,2.4057f,-0.283f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [6.1521f,0f,1.999f,0f,0f,2.3958f,0f,-0.5833f,-1.999f,0f,6.1521f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}