# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0.128f,0f,2.413f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0.128f,0f,2.413f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.64f,0f,2.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [2.6668f,0f,0.4224f,-0.0264f,0f,1f,0f,3.2813f,-0.4224f,0f,2.6668f,-0.2917f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-0.4224f,0f,2.6668f,-0.0199f,0f,1f,0f,2.8313f,-2.6668f,0f,-0.4224f,-0.2955f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [2.6668f,0f,0.4224f,-0.0235f,0f,1f,0f,2.8313f,-0.4224f,0f,2.6668f,-0.2907f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [1.587f,0f,2.1843f,-0.0236f,0f,1f,0f,2.8313f,-2.1843f,0f,1.587f,-0.2931f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [2.1843f,0f,-1.587f,-0.025f,0f,1f,0f,2.8313f,1.587f,0f,2.1843f,-0.2889f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [6.3891f,0f,1.0119f,0f,0f,2.3958f,0f,-0.6875f,-1.0119f,0f,6.3891f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}