# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0.995f,0f,2.8713f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0.995f,0f,2.8713f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.995f,0f,2.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [-1.2744f,0f,0.4141f,-0.0259f,0f,1f,0f,4.0188f,-0.4141f,0f,-1.2744f,0.0547f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-0.4141f,0f,-1.2744f,-0.0296f,0f,1f,0f,3.5688f,1.2744f,0f,-0.4141f,0.0549f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-1.2744f,0f,0.4141f,-0.027f,0f,1f,0f,3.5688f,-0.4141f,0f,-1.2744f,0.0536f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-1.1939f,0f,-0.6083f,-0.0274f,0f,1f,0f,3.5688f,0.6083f,0f,-1.1939f,0.0546f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-0.6083f,0f,1.1939f,-0.0259f,0f,1f,0f,3.5688f,-1.1939f,0f,-0.6083f,0.0531f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-3.0533f,0f,0.9921f,0f,0f,2.3958f,0f,0.05f,-0.9921f,0f,-3.0533f,-0.025f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}