# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0f,0f,2.285f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0f,0f,2.285f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.4267f,0f,2.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [2.6668f,0f,-0.4224f,0.0264f,0f,1f,0f,3.0729f,0.4224f,0f,2.6668f,-0.2917f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [0.4224f,0f,2.6668f,0.0338f,0f,1f,0f,2.6229f,-2.6668f,0f,0.4224f,-0.2933f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [2.6668f,0f,-0.4224f,0.0289f,0f,1f,0f,2.6229f,0.4224f,0f,2.6668f,-0.2898f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [2.1843f,0f,1.587f,0.0295f,0f,1f,0f,2.6229f,-1.587f,0f,2.1843f,-0.2921f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [1.587f,0f,-2.1843f,0.0269f,0f,1f,0f,2.6229f,2.1843f,0f,1.587f,-0.2886f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [6.3891f,0f,-1.0119f,0f,0f,2.3958f,0f,-0.8958f,1.0119f,0f,6.3891f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}