# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0f,0f,2.245f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0f,0f,2.245f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.32f,0f,2.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [2.5679f,0f,-0.8343f,0.0521f,0f,1f,0f,2.9688f,0.8343f,0f,2.5679f,-0.2855f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [0.8343f,0f,2.5679f,0.0597f,0f,1f,0f,2.5188f,-2.5679f,0f,0.8343f,-0.2859f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [2.5679f,0f,-0.8343f,0.0543f,0f,1f,0f,2.5188f,0.8343f,0f,2.5679f,-0.2833f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [2.4057f,0f,1.2258f,0.0552f,0f,1f,0f,2.5188f,-1.2258f,0f,2.4057f,-0.2855f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [1.2258f,0f,-2.4057f,0.0521f,0f,1f,0f,2.5188f,2.4057f,0f,1.2258f,-0.2824f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [6.1521f,0f,-1.999f,0f,0f,2.3958f,0f,-1f,1.999f,0f,6.1521f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}