# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [0.0492f,0f,0.9988f,-0.0624f,0f,1f,0f,3.9688f,-0.9988f,0f,0.0492f,-0.0031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-0.9988f,0f,0.0492f,-0.0633f,0f,1f,0f,3.5188f,-0.0492f,0f,-0.9988f,-0.0057f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [0.0492f,0f,0.9988f,-0.0618f,0f,1f,0f,3.5188f,-0.9988f,0f,0.0492f,-0.0041f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-0.6715f,0f,0.741f,-0.0627f,0f,1f,0f,3.5188f,-0.741f,0f,-0.6715f,-0.0042f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [0.741f,0f,0.6715f,-0.0613f,0f,1f,0f,3.5188f,-0.6715f,0f,0.741f,-0.0034f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [0.1178f,0f,2.3929f,0f,0f,2.3958f,0f,0f,-2.3929f,0f,0.1178f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}