# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [0.2334f,0f,0.9724f,-0.0608f,0f,1f,0f,3.9688f,-0.9724f,0f,0.2334f,-0.0146f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-0.9724f,0f,0.2334f,-0.0612f,0f,1f,0f,3.5188f,-0.2334f,0f,-0.9724f,-0.0174f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [0.2334f,0f,0.9724f,-0.06f,0f,1f,0f,3.5188f,-0.9724f,0f,0.2334f,-0.0155f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-0.5225f,0f,0.8526f,-0.0609f,0f,1f,0f,3.5188f,-0.8526f,0f,-0.5225f,-0.0157f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [0.8526f,0f,0.5225f,-0.0596f,0f,1f,0f,3.5188f,-0.5225f,0f,0.8526f,-0.0147f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [0.5593f,0f,2.3296f,0f,0f,2.3958f,0f,0f,-2.3296f,0f,0.5593f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}