# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [0.5556f,0f,0.8315f,-0.052f,0f,1f,0f,3.9688f,-0.8315f,0f,0.5556f,-0.0347f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-0.8315f,0f,0.5556f,-0.0514f,0f,1f,0f,3.5188f,-0.5556f,0f,-0.8315f,-0.0375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [0.5556f,0f,0.8315f,-0.051f,0f,1f,0f,3.5188f,-0.8315f,0f,0.5556f,-0.0353f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-0.1951f,0f,0.9808f,-0.0516f,0f,1f,0f,3.5188f,-0.9808f,0f,-0.1951f,-0.0358f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [0.9808f,0f,0.1951f,-0.0509f,0f,1f,0f,3.5188f,-0.1951f,0f,0.9808f,-0.0344f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [1.3311f,0f,1.9921f,0f,0f,2.3958f,0f,0f,-1.9921f,0f,1.3311f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}