# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [1.587f,0f,-2.1843f,0.1365f,0f,1f,0f,2.5646f,2.1843f,0f,1.587f,-0.2242f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [2.1843f,0f,1.587f,0.1429f,0f,1f,0f,2.1146f,-1.587f,0f,2.1843f,-0.2201f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [1.587f,0f,-2.1843f,0.137f,0f,1f,0f,2.1146f,2.1843f,0f,1.587f,-0.2211f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [2.6668f,0f,-0.4224f,0.139f,0f,1f,0f,2.1146f,0.4224f,0f,2.6668f,-0.2223f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-0.4224f,0f,-2.6668f,0.1347f,0f,1f,0f,2.1146f,2.6668f,0f,-0.4224f,-0.2217f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [3.8022f,0f,-5.2333f,0f,0f,2.3958f,0f,-1.4042f,5.2333f,0f,3.8022f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}