# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0f,0f,2.0295f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0f,0f,2.0295f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0f,0f,2.0295f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1667f,0f,0f,-0.8125f,0f,1.1f,0f,2.0295f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1667f,0f,0f,0.8125f,0f,1.1f,0f,2.0295f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body1) {transformation: [-1f,0f,0f,0f,0f,0.9429f,0f,1.2634f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [1.2258f,0f,-2.4057f,0.1504f,0f,1f,0f,2.4729f,2.4057f,0f,1.2258f,-0.2016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [2.4057f,0f,1.2258f,0.156f,0f,1f,0f,2.0229f,-1.2258f,0f,2.4057f,-0.1966f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [1.2258f,0f,-2.4057f,0.1503f,0f,1f,0f,2.0229f,2.4057f,0f,1.2258f,-0.1985f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [2.5679f,0f,-0.8343f,0.1525f,0f,1f,0f,2.0229f,0.8343f,0f,2.5679f,-0.1994f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-0.8343f,0f,-2.5679f,0.1481f,0f,1f,0f,2.0229f,2.5679f,0f,-0.8343f,-0.1994f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [2.9368f,0f,-5.7637f,0f,0f,2.3958f,0f,-1.4958f,5.7637f,0f,2.9368f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}