# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0f,0f,1.8384f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0f,0f,1.8384f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0f,0f,1.8384f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1667f,0f,0f,-0.8125f,0f,0.9667f,0f,1.8384f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1667f,0f,0f,0.8125f,0f,0.9667f,0f,1.8384f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body1) {transformation: [-1f,0f,0f,0f,0f,0.8286f,0f,1.1652f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [0.4224f,0f,-2.6668f,0.1667f,0f,1f,0f,2.2896f,2.6668f,0f,0.4224f,-0.1514f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [2.6668f,0f,0.4224f,0.1705f,0f,1f,0f,1.8396f,-0.4224f,0f,2.6668f,-0.1449f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [0.4224f,0f,-2.6668f,0.1657f,0f,1f,0f,1.8396f,2.6668f,0f,0.4224f,-0.1485f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [2.1843f,0f,-1.587f,0.1681f,0f,1f,0f,1.8396f,1.587f,0f,2.1843f,-0.1486f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-1.587f,0f,-2.1843f,0.1639f,0f,1f,0f,1.8396f,2.1843f,0f,-1.587f,-0.15f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [1.0119f,0f,-6.3891f,0f,0f,2.3958f,0f,-1.6792f,6.3891f,0f,1.0119f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}