# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0.9925f,0f,2.8694f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0.9925f,0f,2.8694f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.9925f,0f,2.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [-1.3454f,0f,0.6855f,-0.0428f,0f,1f,0f,4.0438f,-0.6855f,0f,-1.3454f,0.0466f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-0.6855f,0f,-1.3454f,-0.0471f,0f,1f,0f,3.5938f,1.3454f,0f,-0.6855f,0.0462f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-1.3454f,0f,0.6855f,-0.0439f,0f,1f,0f,3.5938f,-0.6855f,0f,-1.3454f,0.0452f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-1.4361f,0f,-0.4666f,-0.0446f,0f,1f,0f,3.5938f,0.4666f,0f,-1.4361f,0.0463f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-0.4666f,0f,1.4361f,-0.0426f,0f,1f,0f,3.5938f,-1.4361f,0f,-0.4666f,0.0449f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-3.2234f,0f,1.6424f,0f,0f,2.3958f,0f,0.075f,-1.6424f,0f,-3.2234f,-0.0375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}