# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0f,0f,1.6473f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0f,0f,1.6473f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0f,0f,1.6473f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1667f,0f,0f,-0.8125f,0f,0.8333f,0f,1.6473f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1667f,0f,0f,0.8125f,0f,0.8333f,0f,1.6473f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body1) {transformation: [-1f,0f,0f,0f,0f,0.7143f,0f,1.067f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [-0.4224f,0f,-2.6668f,0.1667f,0f,1f,0f,2.1062f,2.6668f,0f,-0.4224f,-0.0986f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [2.6668f,0f,-0.4224f,0.1683f,0f,1f,0f,1.6562f,0.4224f,0f,2.6668f,-0.0912f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-0.4224f,0f,-2.6668f,0.1648f,0f,1f,0f,1.6562f,2.6668f,0f,-0.4224f,-0.0961f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [1.587f,0f,-2.1843f,0.1671f,0f,1f,0f,1.6562f,2.1843f,0f,1.587f,-0.0955f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-2.1843f,0f,-1.587f,0.1636f,0f,1f,0f,1.6562f,1.587f,0f,-2.1843f,-0.0981f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-1.0119f,0f,-6.3891f,0f,0f,2.3958f,0f,-1.8625f,6.3891f,0f,-1.0119f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}