# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0f,0f,1.5518f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0f,0f,1.5518f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0f,0f,1.5518f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1667f,0f,0f,-0.8125f,0f,0.7667f,0f,1.5518f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1667f,0f,0f,0.8125f,0f,0.7667f,0f,1.5518f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body1) {transformation: [-1f,0f,0f,0f,0f,0.6571f,0f,1.0179f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [-0.8343f,0f,-2.5679f,0.1605f,0f,1f,0f,2.0146f,2.5679f,0f,-0.8343f,-0.0729f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [2.5679f,0f,-0.8343f,0.1609f,0f,1f,0f,1.5646f,0.8343f,0f,2.5679f,-0.0653f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-0.8343f,0f,-2.5679f,0.1583f,0f,1f,0f,1.5646f,2.5679f,0f,-0.8343f,-0.0707f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [1.2258f,0f,-2.4057f,0.1605f,0f,1f,0f,1.5646f,2.4057f,0f,1.2258f,-0.0698f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-2.4057f,0f,-1.2258f,0.1574f,0f,1f,0f,1.5646f,1.2258f,0f,-2.4057f,-0.0729f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-1.999f,0f,-6.1521f,0f,0f,2.3958f,0f,-1.9542f,6.1521f,0f,-1.999f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}