# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0f,0f,1.1696f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0f,0f,1.1696f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0f,0f,1.1696f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1667f,0f,0f,-0.8125f,0f,0.5f,0f,1.1696f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1667f,0f,0f,0.8125f,0f,0.5f,0f,1.1696f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body1) {transformation: [-1f,0f,0f,0f,0f,0.4286f,0f,0.8214f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [-2.1843f,0f,-1.587f,0.0992f,0f,1f,0f,1.6479f,1.587f,0f,-2.1843f,0.0115f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [1.587f,0f,-2.1843f,0.0951f,0f,1f,0f,1.1979f,2.1843f,0f,1.587f,0.0179f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-2.1843f,0f,-1.587f,0.0961f,0f,1f,0f,1.1979f,1.587f,0f,-2.1843f,0.012f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-0.4224f,0f,-2.6668f,0.0973f,0f,1f,0f,1.1979f,2.6668f,0f,-0.4224f,0.014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-2.6668f,0f,0.4224f,0.0967f,0f,1f,0f,1.1979f,-0.4224f,0f,-2.6668f,0.0097f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-5.2333f,0f,-3.8022f,0f,0f,2.3958f,0f,-2.3208f,3.8022f,0f,-5.2333f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}