# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0f,0f,0.883f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0f,0f,0.883f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0f,0f,0.883f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1667f,0f,0f,-0.8125f,0f,0.3f,0f,0.883f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1667f,0f,0f,0.8125f,0f,0.3f,0f,0.883f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body1) {transformation: [-1f,0f,0f,0f,0f,0.2571f,0f,0.6741f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [-2.6668f,0f,-0.4224f,0.0264f,0f,1f,0f,1.3729f,0.4224f,0f,-2.6668f,0.0417f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [0.4224f,0f,-2.6668f,0.0199f,0f,1f,0f,0.9229f,2.6668f,0f,0.4224f,0.0455f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-2.6668f,0f,-0.4224f,0.0235f,0f,1f,0f,0.9229f,0.4224f,0f,-2.6668f,0.0407f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-1.587f,0f,-2.1843f,0.0236f,0f,1f,0f,0.9229f,2.1843f,0f,-1.587f,0.0431f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-2.1843f,0f,1.587f,0.025f,0f,1f,0f,0.9229f,-1.587f,0f,-2.1843f,0.0389f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-6.3891f,0f,-1.0119f,0f,0f,2.3958f,0f,-2.5958f,1.0119f,0f,-6.3891f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}