# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0.99f,0f,2.8675f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0.99f,0f,2.8675f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.99f,0f,2.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [-1.3591f,0f,0.9875f,-0.0617f,0f,1f,0f,4.0688f,-0.9875f,0f,-1.3591f,0.0349f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-0.9875f,0f,-1.3591f,-0.0663f,0f,1f,0f,3.6188f,1.3591f,0f,-0.9875f,0.0337f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-1.3591f,0f,0.9875f,-0.0626f,0f,1f,0f,3.6188f,-0.9875f,0f,-1.3591f,0.0332f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-1.6593f,0f,-0.2628f,-0.0635f,0f,1f,0f,3.6188f,0.2628f,0f,-1.6593f,0.0343f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-0.2628f,0f,1.6593f,-0.0611f,0f,1f,0f,3.6188f,-1.6593f,0f,-0.2628f,0.0331f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-3.2563f,0f,2.3658f,0f,0f,2.3958f,0f,0.1f,-2.3658f,0f,-3.2563f,-0.05f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}