# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0f,0f,0.6475f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0f,0f,0.6475f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0f,0f,0.6475f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1667f,0f,0f,-0.8125f,0f,0.14f,0f,0.6475f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1667f,0f,0f,0.8125f,0f,0.14f,0f,0.6475f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body1) {transformation: [-1f,0f,0f,0f,0f,0.12f,0f,0.55f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0222f,0f,0f,-0.3687f,0f,0.8f,0f,0.6625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0222f,0f,0f,0.3688f,0f,0.8f,0f,0.6625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [-2.5679f,0f,0.8343f,-0.0521f,0f,1f,0f,1.1188f,-0.8343f,0f,-2.5679f,0.0355f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-0.8343f,0f,-2.5679f,-0.0597f,0f,1f,0f,0.6687f,2.5679f,0f,-0.8343f,0.0359f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-2.5679f,0f,0.8343f,-0.0543f,0f,1f,0f,0.6687f,-0.8343f,0f,-2.5679f,0.0333f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-2.4057f,0f,-1.2258f,-0.0552f,0f,1f,0f,0.6687f,1.2258f,0f,-2.4057f,0.0355f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-1.2258f,0f,2.4057f,-0.0521f,0f,1f,0f,0.6687f,-2.4057f,0f,-1.2258f,0.0324f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-6.1521f,0f,1.999f,0f,0f,2.3958f,0f,-2.85f,-1.999f,0f,-6.1521f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}