# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0f,0f,0.5075f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0f,0f,0.5075f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0f,0f,0.5075f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1667f,0f,0f,-0.8125f,0f,0.0467f,0f,0.5075f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1667f,0f,0f,0.8125f,0f,0.0467f,0f,0.5075f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body1) {transformation: [-1f,0f,0f,0f,0f,0.04f,0f,0.475f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0444f,0f,0f,-0.3687f,0f,0.6f,0f,0.5125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0444f,0f,0f,0.3688f,0f,0.6f,0f,0.5125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [-2.1843f,0f,1.587f,-0.0992f,0f,1f,0f,0.9562f,-1.587f,0f,-2.1843f,0.0115f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-1.587f,0f,-2.1843f,-0.1065f,0f,1f,0f,0.5062f,2.1843f,0f,-1.587f,0.0096f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-2.1843f,0f,1.587f,-0.1006f,0f,1f,0f,0.5062f,-1.587f,0f,-2.1843f,0.0088f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-2.6668f,0f,-0.4224f,-0.1021f,0f,1f,0f,0.5062f,0.4224f,0f,-2.6668f,0.0105f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-0.4224f,0f,2.6668f,-0.0982f,0f,1f,0f,0.5062f,-2.6668f,0f,-0.4224f,0.0086f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-5.2333f,0f,3.8022f,0f,0f,2.3958f,0f,-3.0125f,-3.8022f,0f,-5.2333f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}