# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.4375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.4375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.4375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.4375f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.4375f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body1) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.4375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0667f,0f,0f,-0.3687f,0f,0.4f,0f,0.3625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0667f,0f,0f,0.3688f,0f,0.4f,0f,0.3625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [-1.587f,0f,2.1843f,-0.1365f,0f,1f,0f,0.7938f,-2.1843f,0f,-1.587f,-0.0258f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-2.1843f,0f,-1.587f,-0.1429f,0f,1f,0f,0.3438f,1.587f,0f,-2.1843f,-0.0299f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-1.587f,0f,2.1843f,-0.137f,0f,1f,0f,0.3438f,-2.1843f,0f,-1.587f,-0.0289f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-2.6668f,0f,0.4224f,-0.139f,0f,1f,0f,0.3438f,-0.4224f,0f,-2.6668f,-0.0277f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [0.4224f,0f,2.6668f,-0.1347f,0f,1f,0f,0.3438f,-2.6668f,0f,0.4224f,-0.0283f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-3.8022f,0f,5.2333f,0f,0f,2.3958f,0f,-3.175f,-5.2333f,0f,-3.8022f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}