# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_leg) {transformation: [-1.0778f,0f,0f,-0.3687f,0f,0.3f,0f,0.2875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0778f,0f,0f,0.3688f,0f,0.3f,0f,0.2875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [-1.2258f,0f,2.4057f,-0.1504f,0f,1f,0f,0.7125f,-2.4057f,0f,-1.2258f,-0.0484f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-2.4057f,0f,-1.2258f,-0.156f,0f,1f,0f,0.2625f,1.2258f,0f,-2.4057f,-0.0534f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-1.2258f,0f,2.4057f,-0.1503f,0f,1f,0f,0.2625f,-2.4057f,0f,-1.2258f,-0.0515f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-2.5679f,0f,0.8343f,-0.1525f,0f,1f,0f,0.2625f,-0.8343f,0f,-2.5679f,-0.0506f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [0.8343f,0f,2.5679f,-0.1481f,0f,1f,0f,0.2625f,-2.5679f,0f,0.8343f,-0.0506f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-2.9368f,0f,5.7637f,0f,0f,2.3958f,0f,-3.2562f,-5.7637f,0f,-2.9368f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}