# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_leg) {transformation: [-1.0889f,0f,0f,-0.3687f,0f,0.2f,0f,0.2125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0889f,0f,0f,0.3688f,0f,0.2f,0f,0.2125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [-0.8343f,0f,2.5679f,-0.1605f,0f,1f,0f,0.6313f,-2.5679f,0f,-0.8343f,-0.0729f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-2.5679f,0f,-0.8343f,-0.1653f,0f,1f,0f,0.1812f,0.8343f,0f,-2.5679f,-0.0787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-0.8343f,0f,2.5679f,-0.16f,0f,1f,0f,0.1812f,-2.5679f,0f,-0.8343f,-0.0759f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-2.4057f,0f,1.2258f,-0.1623f,0f,1f,0f,0.1812f,-1.2258f,0f,-2.4057f,-0.0754f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [1.2258f,0f,2.4057f,-0.158f,0f,1f,0f,0.1812f,-2.4057f,0f,1.2258f,-0.0747f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-1.999f,0f,6.1521f,0f,0f,2.3958f,0f,-3.3375f,-6.1521f,0f,-1.999f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}