# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_leg) {transformation: [-1.1f,0f,0f,-0.3687f,0f,0.1f,0f,0.1375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.1f,0f,0f,0.3688f,0f,0.1f,0f,0.1375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [-0.4224f,0f,2.6668f,-0.1667f,0f,1f,0f,0.55f,-2.6668f,0f,-0.4224f,-0.0986f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-2.6668f,0f,-0.4224f,-0.1705f,0f,1f,0f,0.1f,0.4224f,0f,-2.6668f,-0.1051f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-0.4224f,0f,2.6668f,-0.1657f,0f,1f,0f,0.1f,-2.6668f,0f,-0.4224f,-0.1015f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-2.1843f,0f,1.587f,-0.1681f,0f,1f,0f,0.1f,-1.587f,0f,-2.1843f,-0.1014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [1.587f,0f,2.1843f,-0.1639f,0f,1f,0f,0.1f,-2.1843f,0f,1.587f,-0.1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-1.0119f,0f,6.3891f,0f,0f,2.3958f,0f,-3.4187f,-6.3891f,0f,-1.0119f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}