# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0.9875f,0f,2.8656f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0.9875f,0f,2.8656f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.9875f,0f,2.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [-1.3081f,0f,1.3081f,-0.0818f,0f,1f,0f,4.0938f,-1.3081f,0f,-1.3081f,0.0193f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-1.3081f,0f,-1.3081f,-0.0865f,0f,1f,0f,3.6438f,1.3081f,0f,-1.3081f,0.0172f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-1.3081f,0f,1.3081f,-0.0824f,0f,1f,0f,3.6438f,-1.3081f,0f,-1.3081f,0.0172f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-1.85f,0f,0f,-0.0836f,0f,1f,0f,3.6438f,0f,0f,-1.85f,0.0183f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [0f,0f,1.85f,-0.0808f,0f,1f,0f,3.6438f,-1.85f,0f,0f,0.0174f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-3.1341f,0f,3.1341f,0f,0f,2.3958f,0f,0.125f,-3.1341f,0f,-3.1341f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}