# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_leg) {transformation: [0f,0f,0f,-0.3687f,0f,0f,0f,0.0625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [0f,0f,0f,0.3688f,0f,0f,0f,0.0625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [0f,0f,2.7f,-0.1687f,0f,1f,0f,0.4688f,-2.7f,0f,0f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-2.7f,0f,0f,-0.1715f,0f,1f,0f,0.0187f,0f,0f,-2.7f,-0.1321f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [0f,0f,2.7f,-0.1673f,0f,1f,0f,0.0187f,-2.7f,0f,0f,-0.1277f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-1.9092f,0f,1.9092f,-0.1697f,0f,1f,0f,0.0187f,-1.9092f,0f,-1.9092f,-0.128f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [1.9092f,0f,1.9092f,-0.1658f,0f,1f,0f,0.0187f,-1.9092f,0f,1.9092f,-0.1259f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [0f,0f,6.4688f,0f,0f,2.3958f,0f,-3.5f,-6.4688f,0f,0f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}