# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [0f,0f,2.16f,-0.135f,0f,1f,0f,0.4688f,-2.16f,0f,0f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-2.16f,0f,0f,-0.1372f,0f,1f,0f,0.0187f,0f,0f,-2.16f,-0.1306f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [0f,0f,2.16f,-0.1339f,0f,1f,0f,0.0187f,-2.16f,0f,0f,-0.1272f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-1.5274f,0f,1.5274f,-0.1357f,0f,1f,0f,0.0187f,-1.5274f,0f,-1.5274f,-0.1274f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [1.5274f,0f,1.5274f,-0.1326f,0f,1f,0f,0.0187f,-1.5274f,0f,1.5274f,-0.1257f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [0f,0f,5.175f,0f,0f,2.3958f,0f,-3.5f,-5.175f,0f,0f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}