# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [0f,0f,1.62f,-0.1012f,0f,1f,0f,0.4688f,-1.62f,0f,0f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-1.62f,0f,0f,-0.1029f,0f,1f,0f,0.0187f,0f,0f,-1.62f,-0.1292f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [0f,0f,1.62f,-0.1004f,0f,1f,0f,0.0187f,-1.62f,0f,0f,-0.1266f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-1.1455f,0f,1.1455f,-0.1018f,0f,1f,0f,0.0187f,-1.1455f,0f,-1.1455f,-0.1268f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [1.1455f,0f,1.1455f,-0.0995f,0f,1f,0f,0.0187f,-1.1455f,0f,1.1455f,-0.1256f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [0f,0f,3.8813f,0f,0f,2.3958f,0f,-3.5f,-3.8812f,0f,0f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}