# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [0f,0f,1.08f,-0.0675f,0f,1f,0f,0.4688f,-1.08f,0f,0f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-1.08f,0f,0f,-0.0686f,0f,1f,0f,0.0187f,0f,0f,-1.08f,-0.1278f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [0f,0f,1.08f,-0.0669f,0f,1f,0f,0.0187f,-1.08f,0f,0f,-0.1261f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-0.7637f,0f,0.7637f,-0.0679f,0f,1f,0f,0.0187f,-0.7637f,0f,-0.7637f,-0.1262f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [0.7637f,0f,0.7637f,-0.0663f,0f,1f,0f,0.0187f,-0.7637f,0f,0.7637f,-0.1254f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [0f,0f,2.5875f,0f,0f,2.3958f,0f,-3.5f,-2.5875f,0f,0f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}