# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [0f,0f,0.54f,-0.0337f,0f,1f,0f,0.4688f,-0.54f,0f,0f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-0.54f,0f,0f,-0.0343f,0f,1f,0f,0.0187f,0f,0f,-0.54f,-0.1264f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [0f,0f,0.54f,-0.0335f,0f,1f,0f,0.0187f,-0.54f,0f,0f,-0.1255f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-0.3818f,0f,0.3818f,-0.0339f,0f,1f,0f,0.0187f,-0.3818f,0f,-0.3818f,-0.1256f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [0.3818f,0f,0.3818f,-0.0332f,0f,1f,0f,0.0187f,-0.3818f,0f,0.3818f,-0.1252f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [0f,0f,1.2937f,0f,0f,2.3958f,0f,-3.5f,-1.2937f,0f,0f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}