# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0.985f,0f,2.8638f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0.985f,0f,2.8638f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.985f,0f,2.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [-1.1873f,0f,1.6342f,-0.1021f,0f,1f,0f,4.1188f,-1.6342f,0f,-1.1873f,-0.0008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-1.6342f,0f,-1.1873f,-0.1069f,0f,1f,0f,3.6688f,1.1873f,0f,-1.6342f,-0.0039f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-1.1873f,0f,1.6342f,-0.1025f,0f,1f,0f,3.6688f,-1.6342f,0f,-1.1873f,-0.0031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-1.9951f,0f,0.316f,-0.104f,0f,1f,0f,3.6688f,-0.316f,0f,-1.9951f,-0.0022f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [0.316f,0f,1.9951f,-0.1008f,0f,1f,0f,3.6688f,-1.9951f,0f,0.316f,-0.0027f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-2.8446f,0f,3.9153f,0f,0f,2.3958f,0f,0.15f,-3.9153f,0f,-2.8446f,-0.075f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}