# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [0f,0f,1f,0f,0f,1f,0f,0.5494f,-1f,0f,0f,-0.4987f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-1f,0f,0f,-0.001f,0f,1f,0f,0.0994f,0f,0f,-1f,-0.5014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [0f,0f,1f,0.0005f,0f,1f,0f,0.0994f,-1f,0f,0f,-0.4998f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-0.7071f,0f,0.7071f,-0.0003f,0f,1f,0f,0.0994f,-0.7071f,0f,-0.7071f,-0.4998f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [0.7071f,0f,0.7071f,0.0011f,0f,1f,0f,0.0994f,-0.7071f,0f,0.7071f,-0.4991f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [0f,0f,2.3958f,0.0625f,0f,2.3958f,0f,-3.4194f,-2.3958f,0f,0f,-0.4987f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}