# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [0.1423f,0f,0.9898f,0.0006f,0f,1f,0f,0.55f,-0.9898f,0f,0.1423f,-0.5072f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-0.9898f,0f,0.1423f,0f,0f,1f,0f,0.1f,-0.1423f,0f,-0.9898f,-0.51f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [0.1423f,0f,0.9898f,0.0013f,0f,1f,0f,0.1f,-0.9898f,0f,0.1423f,-0.5082f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-0.5993f,0f,0.8005f,0.0005f,0f,1f,0f,0.1f,-0.8005f,0f,-0.5993f,-0.5084f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [0.8005f,0f,0.5993f,0.0018f,0f,1f,0f,0.1f,-0.5993f,0f,0.8005f,-0.5074f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [0.341f,0f,2.3714f,0.0625f,0f,2.3958f,0f,-3.4187f,-2.3714f,0f,0.341f,-0.4983f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}