# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0.9825f,0f,2.8619f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0.9825f,0f,2.8619f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.9825f,0f,2.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [-0.9942f,0f,1.9513f,-0.122f,0f,1f,0f,4.1438f,-1.9513f,0f,-0.9942f,-0.0254f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-1.9513f,0f,-0.9942f,-0.1265f,0f,1f,0f,3.6938f,0.9942f,0f,-1.9513f,-0.0294f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-0.9942f,0f,1.9513f,-0.1219f,0f,1f,0f,3.6938f,-1.9513f,0f,-0.9942f,-0.0279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-2.0828f,0f,0.6767f,-0.1237f,0f,1f,0f,3.6938f,-0.6767f,0f,-2.0828f,-0.0272f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [0.6767f,0f,2.0828f,-0.1202f,0f,1f,0f,3.6938f,-2.0828f,0f,0.6767f,-0.0271f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-2.382f,0f,4.675f,0f,0f,2.3958f,0f,0.175f,-4.675f,0f,-2.382f,-0.0875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}