# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [0.9898f,0f,0.1423f,0.0536f,0f,1f,0f,1.7362f,-0.1423f,0f,0.9898f,0.189f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-0.1423f,0f,0.9898f,0.056f,0f,1f,0f,1.2862f,-0.9898f,0f,-0.1423f,0.1876f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [0.9898f,0f,0.1423f,0.0547f,0f,1f,0f,1.2862f,-0.1423f,0f,0.9898f,0.1894f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [0.5993f,0f,0.8005f,0.0546f,0f,1f,0f,1.2862f,-0.8005f,0f,0.5993f,0.1885f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [0.8005f,0f,-0.5993f,0.0541f,0f,1f,0f,1.2862f,0.5993f,0f,0.8005f,0.19f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [2.3714f,0f,0.341f,0.0625f,0f,2.3958f,0f,-2.2325f,-0.341f,0f,2.3714f,0.2508f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}