# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [1f,0f,0f,0.0625f,0f,1f,0f,1.7369f,0f,0f,1f,0.1887f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [0f,0f,1f,0.0651f,0f,1f,0f,1.2869f,-1f,0f,0f,0.1877f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [1f,0f,0f,0.0635f,0f,1f,0f,1.2869f,0f,0f,1f,0.1893f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [0.7071f,0f,0.7071f,0.0636f,0f,1f,0f,1.2869f,-0.7071f,0f,0.7071f,0.1884f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [0.7071f,0f,-0.7071f,0.0628f,0f,1f,0f,1.2869f,0.7071f,0f,0.7071f,0.1898f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [2.3958f,0f,0f,0.0625f,0f,2.3958f,0f,-2.2319f,0f,0f,2.3958f,0.2512f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}