# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [0.9397f,0f,-0.342f,0.0839f,0f,1f,0f,1.7369f,0.342f,0f,0.9397f,0.1925f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [0.342f,0f,0.9397f,0.0867f,0f,1f,0f,1.2869f,-0.9397f,0f,0.342f,0.1925f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [0.9397f,0f,-0.342f,0.0847f,0f,1f,0f,1.2869f,0.342f,0f,0.9397f,0.1934f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [0.9063f,0f,0.4226f,0.085f,0f,1f,0f,1.2869f,-0.4226f,0f,0.9063f,0.1926f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [0.4226f,0f,-0.9063f,0.0838f,0f,1f,0f,1.2869f,0.9063f,0f,0.4226f,0.1937f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [2.2513f,0f,-0.8194f,0.0625f,0f,2.3958f,0f,-2.2319f,0.8194f,0f,2.2513f,0.2512f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}