# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [0.866f,0f,-0.5f,0.0938f,0f,1f,0f,1.7369f,0.5f,0f,0.866f,0.1971f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [0.5f,0f,0.866f,0.0965f,0f,1f,0f,1.2869f,-0.866f,0f,0.5f,0.1975f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [0.866f,0f,-0.5f,0.0944f,0f,1f,0f,1.2869f,0.5f,0f,0.866f,0.1981f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [0.9659f,0f,0.2588f,0.0949f,0f,1f,0f,1.2869f,-0.2588f,0f,0.9659f,0.1974f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [0.2588f,0f,-0.9659f,0.0935f,0f,1f,0f,1.2869f,0.9659f,0f,0.2588f,0.1982f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [2.0749f,0f,-1.1979f,0.0625f,0f,2.3958f,0f,-2.2319f,1.1979f,0f,2.0749f,0.2512f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}