# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0.98f,0f,2.86f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0.98f,0f,2.86f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.98f,0f,2.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [-0.7293f,0f,2.2445f,-0.1403f,0f,1f,0f,4.1688f,-2.2445f,0f,-0.7293f,-0.0544f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-2.2445f,0f,-0.7293f,-0.1445f,0f,1f,0f,3.7188f,0.7293f,0f,-2.2445f,-0.0595f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-0.7293f,0f,2.2445f,-0.1398f,0f,1f,0f,3.7188f,-2.2445f,0f,-0.7293f,-0.0571f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-2.1028f,0f,1.0714f,-0.1419f,0f,1f,0f,3.7188f,-1.0714f,0f,-2.1028f,-0.0566f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [1.0714f,0f,2.1028f,-0.1381f,0f,1f,0f,3.7188f,-2.1028f,0f,1.0714f,-0.056f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-1.7472f,0f,5.3774f,0f,0f,2.3958f,0f,0.2f,-5.3774f,0f,-1.7472f,-0.1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}