# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [0.766f,0f,-0.6428f,0.1027f,0f,1f,0f,1.7369f,0.6428f,0f,0.766f,0.2034f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [0.6428f,0f,0.766f,0.1053f,0f,1f,0f,1.2869f,-0.766f,0f,0.6428f,0.2043f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [0.766f,0f,-0.6428f,0.1031f,0f,1f,0f,1.2869f,0.6428f,0f,0.766f,0.2044f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [0.9962f,0f,0.0872f,0.1037f,0f,1f,0f,1.2869f,-0.0872f,0f,0.9962f,0.2038f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [0.0872f,0f,-0.9962f,0.1022f,0f,1f,0f,1.2869f,0.9962f,0f,0.0872f,0.2044f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [1.8353f,0f,-1.54f,0.0625f,0f,2.3958f,0f,-2.2319f,1.54f,0f,1.8353f,0.2512f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}