# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [0.6428f,0f,-0.766f,0.1104f,0f,1f,0f,1.7369f,0.766f,0f,0.6428f,0.2111f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [0.766f,0f,0.6428f,0.1128f,0f,1f,0f,1.2869f,-0.6428f,0f,0.766f,0.2124f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [0.6428f,0f,-0.766f,0.1106f,0f,1f,0f,1.2869f,0.766f,0f,0.6428f,0.2122f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [0.9962f,0f,-0.0872f,0.1113f,0f,1f,0f,1.2869f,0.0872f,0f,0.9962f,0.2117f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-0.0872f,0f,-0.9962f,0.1098f,0f,1f,0f,1.2869f,0.9962f,0f,-0.0872f,0.212f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [1.54f,0f,-1.8353f,0.0625f,0f,2.3958f,0f,-2.2319f,1.8353f,0f,1.54f,0.2512f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}