# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [0f,0f,-0.3333f,0.0833f,0f,0.3333f,0f,-0.909f,0.3333f,0f,0f,0.2512f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [0.3333f,0f,0f,0.0837f,0f,0.3333f,0f,-1.059f,0f,0f,0.3333f,0.2521f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [0f,0f,-0.3333f,0.0832f,0f,0.3333f,0f,-1.059f,0.3333f,0f,0f,0.2516f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [0.2357f,0f,-0.2357f,0.0834f,0f,0.3333f,0f,-1.059f,0.2357f,0f,0.2357f,0.2516f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-0.2357f,0f,-0.2357f,0.083f,0f,0.3333f,0f,-1.059f,0.2357f,0f,-0.2357f,0.2514f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [0f,0f,-0.7986f,0.0625f,0f,0.7986f,0f,-2.2319f,0.7986f,0f,0f,0.2512f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}