# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [0f,0f,-0.1667f,0.0729f,0f,0.1667f,0f,-1.5704f,0.1667f,0f,0f,0.2512f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [0.1667f,0f,0f,0.0731f,0f,0.1667f,0f,-1.6454f,0f,0f,0.1667f,0.2517f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [0f,0f,-0.1667f,0.0728f,0f,0.1667f,0f,-1.6454f,0.1667f,0f,0f,0.2514f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [0.1179f,0f,-0.1179f,0.073f,0f,0.1667f,0f,-1.6454f,0.1179f,0f,0.1179f,0.2514f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-0.1179f,0f,-0.1179f,0.0727f,0f,0.1667f,0f,-1.6454f,0.1179f,0f,-0.1179f,0.2513f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [0f,0f,-0.3993f,0.0625f,0f,0.3993f,0f,-2.2319f,0.3993f,0f,0f,0.2512f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}