# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0.9775f,0f,2.8581f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0.9775f,0f,2.8581f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.9775f,0f,2.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [-0.3958f,0f,2.4989f,-0.1562f,0f,1f,0f,4.1938f,-2.4989f,0f,-0.3958f,-0.0878f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-2.4989f,0f,-0.3958f,-0.1598f,0f,1f,0f,3.7438f,0.3958f,0f,-2.4989f,-0.0939f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-0.3958f,0f,2.4989f,-0.1553f,0f,1f,0f,3.7438f,-2.4989f,0f,-0.3958f,-0.0905f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-2.0468f,0f,1.4871f,-0.1575f,0f,1f,0f,3.7438f,-1.4871f,0f,-2.0468f,-0.0904f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [1.4871f,0f,2.0468f,-0.1536f,0f,1f,0f,3.7438f,-2.0468f,0f,1.4871f,-0.0891f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-0.9482f,0f,5.9868f,0f,0f,2.3958f,0f,0.225f,-5.9868f,0f,-0.9482f,-0.1125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}