# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players set @s aj.start_phase1.frame 0
tag @s add aj.transforms_only
execute at @s run function warden:ancient_ring/animations/start_phase1/zzz/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only
tag @s remove warden.ancient_ring.animation.start_phase1.playing