# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$kill $(hexadecagon)
$kill $(line90)
$kill $(line0)
$kill $(line1)
$kill $(line2)
$kill $(ring)