# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [0f,0f,2f,-0.125f,0f,2f,0f,1.0104f,-2f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-2f,0f,0f,-0.127f,0f,2f,0f,0.1417f,0f,0f,-2f,-0.0052f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [0f,0f,2f,-0.1239f,0f,2f,0f,0.1417f,-2f,0f,0f,-0.002f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-1.4142f,0f,1.4142f,-0.1257f,0f,2f,0f,0.1417f,-1.4142f,0f,-1.4142f,-0.0022f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [1.4142f,0f,1.4142f,-0.1228f,0f,2f,0f,0.1417f,-1.4142f,0f,1.4142f,-0.0007f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [0f,0f,4.7917f,0f,0f,4.7917f,0f,-6.8958f,-4.7917f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}