# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [0.891f,0f,0.454f,-0.0284f,0f,1f,0f,0.5156f,-0.454f,0f,0.891f,-0.0557f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-0.454f,0f,0.891f,-0.0265f,0f,1f,0f,0.0812f,-0.891f,0f,-0.454f,-0.0578f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [0.891f,0f,0.454f,-0.0272f,0f,1f,0f,0.0812f,-0.454f,0f,0.891f,-0.0557f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [0.309f,0f,0.9511f,-0.0276f,0f,1f,0f,0.0812f,-0.9511f,0f,0.309f,-0.0565f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [0.9511f,0f,-0.309f,-0.0276f,0f,1f,0f,0.0812f,0.309f,0f,0.9511f,-0.0549f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [2.1347f,0f,1.0877f,0f,0f,2.3958f,0f,-3.4375f,-1.0877f,0f,2.1347f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}