# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [0.5878f,0f,-0.809f,0.0506f,0f,1f,0f,0.5156f,0.809f,0f,0.5878f,-0.0367f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [0.809f,0f,0.5878f,0.0529f,0f,1f,0f,0.0812f,-0.5878f,0f,0.809f,-0.0352f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [0.5878f,0f,-0.809f,0.0507f,0f,1f,0f,0.0812f,0.809f,0f,0.5878f,-0.0356f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [0.9877f,0f,-0.1564f,0.0515f,0f,1f,0f,0.0812f,0.1564f,0f,0.9877f,-0.0361f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-0.1564f,0f,-0.9877f,0.0499f,0f,1f,0f,0.0812f,0.9877f,0f,-0.1564f,-0.0358f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [1.4082f,0f,-1.9383f,0f,0f,2.3958f,0f,-3.4375f,1.9383f,0f,1.4082f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}