# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [-0.9511f,0f,-0.309f,0.0193f,0f,1f,0f,0.5156f,0.309f,0f,-0.9511f,0.0594f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [0.309f,0f,-0.9511f,0.0171f,0f,1f,0f,0.0812f,0.9511f,0f,0.309f,0.0612f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-0.9511f,0f,-0.309f,0.0182f,0f,1f,0f,0.0812f,0.309f,0f,-0.9511f,0.0593f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-0.454f,0f,-0.891f,0.0184f,0f,1f,0f,0.0812f,0.891f,0f,-0.454f,0.0601f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-0.891f,0f,0.454f,0.0186f,0f,1f,0f,0.0812f,-0.454f,0f,-0.891f,0.0585f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-2.2786f,0f,-0.7404f,0f,0f,2.3958f,0f,-3.4375f,0.7404f,0f,-2.2786f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}