# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [-2.1213f,0f,2.1213f,-0.1326f,0f,3f,0f,1.5052f,-2.1213f,0f,-2.1213f,0.1326f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-2.1213f,0f,-2.1213f,-0.1403f,0f,3f,0f,0.2021f,2.1213f,0f,-2.1213f,0.1292f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-2.1213f,0f,2.1213f,-0.1336f,0f,3f,0f,0.2021f,-2.1213f,0f,-2.1213f,0.1293f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-3f,0f,0f,-0.1356f,0f,3f,0f,0.2021f,0f,0f,-3f,0.131f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [0f,0f,3f,-0.131f,0f,3f,0f,0.2021f,-3f,0f,0f,0.1295f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-5.0823f,0f,5.0823f,0f,0f,7.1875f,0f,-10.3542f,-5.0823f,0f,-5.0823f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}