# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [0.454f,0f,0.891f,-0.0557f,0f,1f,0f,3.9688f,-0.891f,0f,0.454f,-0.0284f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-0.891f,0f,0.454f,-0.0554f,0f,1f,0f,3.5188f,-0.454f,0f,-0.891f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [0.454f,0f,0.891f,-0.0548f,0f,1f,0f,3.5188f,-0.891f,0f,0.454f,-0.029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-0.309f,0f,0.9511f,-0.0555f,0f,1f,0f,3.5188f,-0.9511f,0f,-0.309f,-0.0295f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [0.9511f,0f,0.309f,-0.0546f,0f,1f,0f,3.5188f,-0.309f,0f,0.9511f,-0.0282f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [1.0877f,0f,2.1347f,0f,0f,2.3958f,0f,0f,-2.1347f,0f,1.0877f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}