# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [0.1564f,0f,-0.9877f,0.0617f,0f,1f,0f,3.9688f,0.9877f,0f,0.1564f,-0.0098f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [0.9877f,0f,0.1564f,0.0631f,0f,1f,0f,3.5188f,-0.1564f,0f,0.9877f,-0.0074f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [0.1564f,0f,-0.9877f,0.0614f,0f,1f,0f,3.5188f,0.9877f,0f,0.1564f,-0.0087f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [0.809f,0f,-0.5878f,0.0622f,0f,1f,0f,3.5188f,0.5878f,0f,0.809f,-0.0088f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-0.5878f,0f,-0.809f,0.0607f,0f,1f,0f,3.5188f,0.809f,0f,-0.5878f,-0.0093f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [0.3748f,0f,-2.3663f,0f,0f,2.3958f,0f,0f,2.3663f,0f,0.3748f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}