# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [-0.809f,0f,0.5878f,-0.0367f,0f,1f,0f,3.9688f,-0.5878f,0f,-0.809f,0.0506f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-0.5878f,0f,-0.809f,-0.0394f,0f,1f,0f,3.5188f,0.809f,0f,-0.5878f,0.0499f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-0.809f,0f,0.5878f,-0.0372f,0f,1f,0f,3.5188f,-0.5878f,0f,-0.809f,0.0495f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-0.9877f,0f,-0.1564f,-0.0378f,0f,1f,0f,3.5188f,0.1564f,0f,-0.9877f,0.0502f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-0.1564f,0f,0.9877f,-0.0364f,0f,1f,0f,3.5188f,-0.9877f,0f,-0.1564f,0.0495f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-1.9383f,0f,1.4082f,0f,0f,2.3958f,0f,0f,-1.4082f,0f,-1.9383f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}