# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove warden.ancient_warden.animation.idle.playing
tag @s remove warden.ancient_warden.animation.death.playing
tag @s remove warden.ancient_warden.animation.spawn.playing
tag @s remove warden.ancient_warden.animation.shield_attack_start.playing