# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=warden.ancient_ring.animation.idle.playing] run function warden:ancient_ring/animations/idle/zzz/on_tick
execute if entity @s[tag=warden.ancient_ring.animation.small_to_big.playing] run function warden:ancient_ring/animations/small_to_big/zzz/on_tick
execute if entity @s[tag=warden.ancient_ring.animation.big_to_small.playing] run function warden:ancient_ring/animations/big_to_small/zzz/on_tick
execute if entity @s[tag=warden.ancient_ring.animation.idle2.playing] run function warden:ancient_ring/animations/idle2/zzz/on_tick
execute on passengers run rotate @s ~ ~