# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=warden.ancient_ring.animation.idle.playing] run function warden:ancient_ring/animations/idle/zzz/on_tick
execute if entity @s[tag=warden.ancient_ring.animation.start_phase1.playing] run function warden:ancient_ring/animations/start_phase1/zzz/on_tick
execute if entity @s[tag=warden.ancient_ring.animation.idle2.playing] run function warden:ancient_ring/animations/idle2/zzz/on_tick
execute on passengers run rotate @s ~ ~