# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove warden.ancient_ring.animation.idle.playing
tag @s remove warden.ancient_ring.animation.small_to_big.playing
tag @s remove warden.ancient_ring.animation.big_to_small.playing
tag @s remove warden.ancient_ring.animation.idle2.playing