# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$function warden:ancient_ring/animations/big_to_small/zzz/frames/$(frame) with storage animated_java:temp entry.data.uuids_by_name
return 1