# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
execute if score @s aj.shield_attack_start.frame matches 47.. run scoreboard players set @s aj.shield_attack_start.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.shield_attack_start.frame
execute at @s run function warden:ancient_warden/animations/shield_attack_start/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.shield_attack_start.frame 1