# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.5156f,0f,0f,-1f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [0f,0f,-1f,-0.0026f,0f,1f,0f,0.0812f,1f,0f,0f,0.0635f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-1f,0f,0f,-0.001f,0f,1f,0f,0.0812f,0f,0f,-1f,0.062f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-0.7071f,0f,-0.7071f,-0.0011f,0f,1f,0f,0.0812f,0.7071f,0f,-0.7071f,0.0628f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-0.7071f,0f,0.7071f,-0.0003f,0f,1f,0f,0.0812f,-0.7071f,0f,-0.7071f,0.0614f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-2.3958f,0f,0f,0f,0f,2.3958f,0f,-3.4375f,0f,0f,-2.3958f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}