# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [2.8284f,0f,2.8284f,-0.1768f,0f,4f,0f,2f,-2.8284f,0f,2.8284f,-0.1768f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-2.8284f,0f,2.8284f,-0.1723f,0f,4f,0f,0.2625f,-2.8284f,0f,-2.8284f,-0.187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [2.8284f,0f,2.8284f,-0.1724f,0f,4f,0f,0.2625f,-2.8284f,0f,2.8284f,-0.1782f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [0f,0f,4f,-0.1747f,0f,4f,0f,0.2625f,-4f,0f,0f,-0.1808f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [4f,0f,0f,-0.1727f,0f,4f,0f,0.2625f,0f,0f,4f,-0.1747f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [6.7764f,0f,6.7764f,0f,0f,9.5833f,0f,-13.8125f,-6.7764f,0f,6.7764f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}