# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [-0.6257f,0f,-3.9508f,0.2469f,0f,4f,0f,2f,3.9508f,0f,-0.6257f,0.0391f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [3.9508f,0f,-0.6257f,0.2493f,0f,4f,0f,0.2625f,0.6257f,0f,3.9508f,0.0501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-0.6257f,0f,-3.9508f,0.2442f,0f,4f,0f,0.2625f,3.9508f,0f,-0.6257f,0.0428f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [2.3511f,0f,-3.2361f,0.2476f,0f,4f,0f,0.2625f,3.2361f,0f,2.3511f,0.0436f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-3.2361f,0f,-2.3511f,0.2424f,0f,4f,0f,0.2625f,2.3511f,0f,-3.2361f,0.0398f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-1.4992f,0f,-9.4653f,0f,0f,9.5833f,0f,-13.8125f,9.4653f,0f,-1.4992f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}