# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [-1.7678f,0f,1.7678f,-0.1105f,0f,2.5f,0f,1.2578f,-1.7678f,0f,-1.7678f,0.1105f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-1.7678f,0f,-1.7678f,-0.1169f,0f,2.5f,0f,0.1719f,1.7678f,0f,-1.7678f,0.1077f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-1.7678f,0f,1.7678f,-0.1113f,0f,2.5f,0f,0.1719f,-1.7678f,0f,-1.7678f,0.1078f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-2.5f,0f,0f,-0.113f,0f,2.5f,0f,0.1719f,0f,0f,-2.5f,0.1092f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [0f,0f,2.5f,-0.1092f,0f,2.5f,0f,0.1719f,-2.5f,0f,0f,0.1079f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-4.2353f,0f,4.2353f,0f,0f,5.9896f,0f,-8.625f,-4.2353f,0f,-4.2353f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}