# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0f,0f,1.3324f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0f,0f,1.3324f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.4248f,0f,1.1731f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1667f,0f,0f,-0.8125f,0f,0.5085f,0f,1.1731f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1667f,0f,0f,0.8125f,0f,0.5085f,0f,1.1731f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body1) {transformation: [-1f,0f,0f,0f,0f,0.4359f,0f,0.8189f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [2.5679f,0f,0.8343f,-0.0521f,0f,1f,0f,2.0146f,-0.8343f,0f,2.5679f,-0.2855f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-0.8343f,0f,2.5679f,-0.0463f,0f,1f,0f,1.5646f,-2.5679f,0f,-0.8343f,-0.2903f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [2.5679f,0f,0.8343f,-0.0491f,0f,1f,0f,1.5646f,-0.8343f,0f,2.5679f,-0.285f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [1.2258f,0f,2.4057f,-0.0496f,0f,1f,0f,1.5646f,-2.4057f,0f,1.2258f,-0.2873f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [2.4057f,0f,-1.2258f,-0.0503f,0f,1f,0f,1.5646f,1.2258f,0f,2.4057f,-0.283f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [6.1521f,0f,1.999f,0f,0f,2.3958f,0f,-1.9542f,-1.999f,0f,6.1521f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}