# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0f,0f,0.4821f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0f,0f,0.4821f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.0035f,0f,0.4808f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1667f,0f,0f,-0.8125f,0f,0.0299f,0f,0.4808f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1667f,0f,0f,0.8125f,0f,0.0299f,0f,0.4808f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body1) {transformation: [-1f,0f,0f,0f,0f,0.0256f,0f,0.4599f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0909f,0f,0f,-0.3687f,0f,0.1818f,0f,0.1875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0909f,0f,0f,0.3688f,0f,0.1818f,0f,0.1875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [-1.2744f,0f,0.4141f,-0.0259f,0f,1f,0f,0.6313f,-0.4141f,0f,-1.2744f,-0.0453f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-0.4141f,0f,-1.2744f,-0.0296f,0f,1f,0f,0.1812f,1.2744f,0f,-0.4141f,-0.0451f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-1.2744f,0f,0.4141f,-0.027f,0f,1f,0f,0.1812f,-0.4141f,0f,-1.2744f,-0.0464f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-1.1939f,0f,-0.6083f,-0.0274f,0f,1f,0f,0.1812f,0.6083f,0f,-1.1939f,-0.0454f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-0.6083f,0f,1.1939f,-0.0259f,0f,1f,0f,0.1812f,-1.1939f,0f,-0.6083f,-0.0469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-3.0533f,0f,0.9921f,0f,0f,2.3958f,0f,-3.3375f,-0.9921f,0f,-3.0533f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}