# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0f,0f,1.4924f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0f,0f,1.4924f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.5054f,0f,1.3029f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1667f,0f,0f,-0.8125f,0f,0.5983f,0f,1.3029f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1667f,0f,0f,0.8125f,0f,0.5983f,0f,1.3029f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body1) {transformation: [-1f,0f,0f,0f,0f,0.5128f,0f,0.8862f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [2.6668f,0f,-0.4224f,0.0264f,0f,1f,0f,2.2896f,0.4224f,0f,2.6668f,-0.2917f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [0.4224f,0f,2.6668f,0.0338f,0f,1f,0f,1.8396f,-2.6668f,0f,0.4224f,-0.2933f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [2.6668f,0f,-0.4224f,0.0289f,0f,1f,0f,1.8396f,0.4224f,0f,2.6668f,-0.2898f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [2.1843f,0f,1.587f,0.0295f,0f,1f,0f,1.8396f,-1.587f,0f,2.1843f,-0.2921f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [1.587f,0f,-2.1843f,0.0269f,0f,1f,0f,1.8396f,2.1843f,0f,1.587f,-0.2886f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [6.3891f,0f,-1.0119f,0f,0f,2.3958f,0f,-1.6792f,1.0119f,0f,6.3891f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}