# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0f,0f,1.5994f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0f,0f,1.5994f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.56f,0f,1.3894f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1667f,0f,0f,-0.8125f,0f,0.6581f,0f,1.3894f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1667f,0f,0f,0.8125f,0f,0.6581f,0f,1.3894f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body1) {transformation: [-1f,0f,0f,0f,0f,0.5641f,0f,0.9311f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [2.4057f,0f,-1.2258f,0.0766f,0f,1f,0f,2.4729f,1.2258f,0f,2.4057f,-0.2754f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [1.2258f,0f,2.4057f,0.0841f,0f,1f,0f,2.0229f,-2.4057f,0f,1.2258f,-0.2746f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [2.4057f,0f,-1.2258f,0.0784f,0f,1f,0f,2.0229f,1.2258f,0f,2.4057f,-0.2728f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [2.5679f,0f,0.8343f,0.0797f,0f,1f,0f,2.0229f,-0.8343f,0f,2.5679f,-0.2748f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [0.8343f,0f,-2.5679f,0.0761f,0f,1f,0f,2.0229f,2.5679f,0f,0.8343f,-0.2723f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [5.7637f,0f,-2.9368f,0f,0f,2.3958f,0f,-1.4958f,2.9368f,0f,5.7637f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}