# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0f,0f,1.653f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0f,0f,1.653f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.5876f,0f,1.4327f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1667f,0f,0f,-0.8125f,0f,0.688f,0f,1.4327f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1667f,0f,0f,0.8125f,0f,0.688f,0f,1.4327f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body1) {transformation: [-1f,0f,0f,0f,0f,0.5897f,0f,0.9535f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [2.1843f,0f,-1.587f,0.0992f,0f,1f,0f,2.5646f,1.587f,0f,2.1843f,-0.2615f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [1.587f,0f,2.1843f,0.1065f,0f,1f,0f,2.1146f,-2.1843f,0f,1.587f,-0.2596f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [2.1843f,0f,-1.587f,0.1006f,0f,1f,0f,2.1146f,1.587f,0f,2.1843f,-0.2588f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [2.6668f,0f,0.4224f,0.1021f,0f,1f,0f,2.1146f,-0.4224f,0f,2.6668f,-0.2605f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [0.4224f,0f,-2.6668f,0.0982f,0f,1f,0f,2.1146f,2.6668f,0f,0.4224f,-0.2586f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [5.2333f,0f,-3.8022f,0f,0f,2.3958f,0f,-1.4042f,3.8022f,0f,5.2333f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}