# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0f,0f,1.7067f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0f,0f,1.7067f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.6154f,0f,1.476f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1667f,0f,0f,-0.8125f,0f,0.7179f,0f,1.476f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1667f,0f,0f,0.8125f,0f,0.7179f,0f,1.476f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body1) {transformation: [-1f,0f,0f,0f,0f,0.6154f,0f,0.976f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [1.9092f,0f,-1.9092f,0.1193f,0f,1f,0f,2.6563f,1.9092f,0f,1.9092f,-0.2443f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [1.9092f,0f,1.9092f,0.1263f,0f,1f,0f,2.2063f,-1.9092f,0f,1.9092f,-0.2413f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [1.9092f,0f,-1.9092f,0.1203f,0f,1f,0f,2.2063f,1.9092f,0f,1.9092f,-0.2414f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [2.7f,0f,0f,0.1221f,0f,1f,0f,2.2063f,0f,0f,2.7f,-0.2429f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [0f,0f,-2.7f,0.1179f,0f,1f,0f,2.2063f,2.7f,0f,0f,-0.2416f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [4.5741f,0f,-4.5741f,0f,0f,2.3958f,0f,-1.3125f,4.5741f,0f,4.5741f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}