# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0f,0f,1.7596f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0f,0f,1.7596f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.641f,0f,1.5192f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1667f,0f,0f,-0.8125f,0f,0.7479f,0f,1.5192f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1667f,0f,0f,0.8125f,0f,0.7479f,0f,1.5192f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body1) {transformation: [-1f,0f,0f,0f,0f,0.641f,0f,0.9984f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [1.587f,0f,-2.1843f,0.1365f,0f,1f,0f,2.7604f,2.1843f,0f,1.587f,-0.2242f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [2.1843f,0f,1.587f,0.1429f,0f,1f,0f,2.3104f,-1.587f,0f,2.1843f,-0.2201f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [1.587f,0f,-2.1843f,0.137f,0f,1f,0f,2.3104f,2.1843f,0f,1.587f,-0.2211f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [2.6668f,0f,-0.4224f,0.139f,0f,1f,0f,2.3104f,0.4224f,0f,2.6668f,-0.2223f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-0.4224f,0f,-2.6668f,0.1347f,0f,1f,0f,2.3104f,2.6668f,0f,-0.4224f,-0.2217f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [3.8022f,0f,-5.2333f,0f,0f,2.3958f,0f,-1.2083f,5.2333f,0f,3.8022f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}