# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0f,0f,1.8654f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0f,0f,1.8654f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.6923f,0f,1.6058f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1667f,0f,0f,-0.8125f,0f,0.8077f,0f,1.6058f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1667f,0f,0f,0.8125f,0f,0.8077f,0f,1.6058f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body1) {transformation: [-1f,0f,0f,0f,0f,0.6923f,0f,1.0433f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [0.8343f,0f,-2.5679f,0.1605f,0f,1f,0f,2.9688f,2.5679f,0f,0.8343f,-0.1771f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [2.5679f,0f,0.8343f,0.1653f,0f,1f,0f,2.5188f,-0.8343f,0f,2.5679f,-0.1713f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [0.8343f,0f,-2.5679f,0.16f,0f,1f,0f,2.5188f,2.5679f,0f,0.8343f,-0.1741f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [2.4057f,0f,-1.2258f,0.1623f,0f,1f,0f,2.5188f,1.2258f,0f,2.4057f,-0.1746f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-1.2258f,0f,-2.4057f,0.158f,0f,1f,0f,2.5188f,2.4057f,0f,-1.2258f,-0.1753f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [1.999f,0f,-6.1521f,0f,0f,2.3958f,0f,-1f,6.1521f,0f,1.999f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}