# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0f,0f,0.528f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0f,0f,0.528f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.0105f,0f,0.524f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1667f,0f,0f,-0.8125f,0f,0.0598f,0f,0.524f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1667f,0f,0f,0.8125f,0f,0.0598f,0f,0.524f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body1) {transformation: [-1f,0f,0f,0f,0f,0.0513f,0f,0.4824f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0818f,0f,0f,-0.3687f,0f,0.2636f,0f,0.25f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0818f,0f,0f,0.3688f,0f,0.2636f,0f,0.25f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [-1.3454f,0f,0.6855f,-0.0428f,0f,1f,0f,0.7125f,-0.6855f,0f,-1.3454f,-0.0409f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-0.6855f,0f,-1.3454f,-0.0471f,0f,1f,0f,0.2625f,1.3454f,0f,-0.6855f,-0.0413f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-1.3454f,0f,0.6855f,-0.0439f,0f,1f,0f,0.2625f,-0.6855f,0f,-1.3454f,-0.0423f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-1.4361f,0f,-0.4666f,-0.0446f,0f,1f,0f,0.2625f,0.4666f,0f,-1.4361f,-0.0412f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-0.4666f,0f,1.4361f,-0.0426f,0f,1f,0f,0.2625f,-1.4361f,0f,-0.4666f,-0.0426f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-3.2234f,0f,1.6424f,0f,0f,2.3958f,0f,-3.2562f,-1.6424f,0f,-3.2234f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}