# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0.8718f,0f,2.5625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0.8718f,0f,2.5625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.8718f,0f,1.9087f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1667f,0f,0f,-0.8125f,0f,1.0171f,0f,1.9087f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1667f,0f,0f,0.8125f,0f,1.0171f,0f,1.9087f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body1) {transformation: [-1f,0f,0f,0f,0f,0.8718f,0f,1.2003f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [-1.9092f,0f,-1.9092f,0.1193f,0f,1f,0f,3.6979f,1.9092f,0f,-1.9092f,-0.0057f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [1.9092f,0f,-1.9092f,0.1163f,0f,1f,0f,3.2479f,1.9092f,0f,1.9092f,0.0013f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-1.9092f,0f,-1.9092f,0.1164f,0f,1f,0f,3.2479f,1.9092f,0f,-1.9092f,-0.0047f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [0f,0f,-2.7f,0.1179f,0f,1f,0f,3.2479f,2.7f,0f,0f,-0.0029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-2.7f,0f,0f,0.1166f,0f,1f,0f,3.2479f,0f,0f,-2.7f,-0.0071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-4.5741f,0f,-4.5741f,0f,0f,2.3958f,0f,-0.2708f,4.5741f,0f,-4.5741f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}