# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0.9231f,0f,2.6875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0.9231f,0f,2.6875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.9231f,0f,1.9952f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1667f,0f,0f,-0.8125f,0f,1.0769f,0f,1.9952f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1667f,0f,0f,0.8125f,0f,1.0769f,0f,1.9952f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body1) {transformation: [-1f,0f,0f,0f,0f,0.9231f,0f,1.2452f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [-2.4057f,0f,-1.2258f,0.0766f,0f,1f,0f,3.9063f,1.2258f,0f,-2.4057f,0.0254f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [1.2258f,0f,-2.4057f,0.0716f,0f,1f,0f,3.4563f,2.4057f,0f,1.2258f,0.031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-2.4057f,0f,-1.2258f,0.0735f,0f,1f,0f,3.4563f,1.2258f,0f,-2.4057f,0.0253f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-0.8343f,0f,-2.5679f,0.0744f,0f,1f,0f,3.4563f,2.5679f,0f,-0.8343f,0.0275f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-2.5679f,0f,0.8343f,0.0744f,0f,1f,0f,3.4563f,-0.8343f,0f,-2.5679f,0.0231f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-5.7637f,0f,-2.9368f,0f,0f,2.3958f,0f,-0.0625f,2.9368f,0f,-5.7637f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}