# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0f,0f,0.5752f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0f,0f,0.5752f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.0211f,0f,0.5673f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1667f,0f,0f,-0.8125f,0f,0.0897f,0f,0.5673f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1667f,0f,0f,0.8125f,0f,0.0897f,0f,0.5673f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body1) {transformation: [-1f,0f,0f,0f,0f,0.0769f,0f,0.5048f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0727f,0f,0f,-0.3687f,0f,0.3455f,0f,0.3125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0727f,0f,0f,0.3688f,0f,0.3455f,0f,0.3125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [-1.3591f,0f,0.9875f,-0.0617f,0f,1f,0f,0.7938f,-0.9875f,0f,-1.3591f,-0.0401f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-0.9875f,0f,-1.3591f,-0.0663f,0f,1f,0f,0.3438f,1.3591f,0f,-0.9875f,-0.0413f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-1.3591f,0f,0.9875f,-0.0626f,0f,1f,0f,0.3438f,-0.9875f,0f,-1.3591f,-0.0418f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-1.6593f,0f,-0.2628f,-0.0635f,0f,1f,0f,0.3438f,0.2628f,0f,-1.6593f,-0.0407f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [-0.2628f,0f,1.6593f,-0.0611f,0f,1f,0f,0.3438f,-1.6593f,0f,-0.2628f,-0.0419f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-3.2563f,0f,2.3658f,0f,0f,2.3958f,0f,-3.175f,-2.3658f,0f,-3.2563f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}