# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hexadecagon) {transformation: [-0.5191f,0f,1.5978f,-0.0999f,0f,1f,0f,3.9688f,-1.5978f,0f,-0.5191f,0.0324f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-1.5978f,0f,-0.5191f,-0.1028f,0f,1f,0f,3.5188f,0.5191f,0f,-1.5978f,0.0288f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-0.5191f,0f,1.5978f,-0.0995f,0f,1f,0f,3.5188f,-1.5978f,0f,-0.5191f,0.0305f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-1.4969f,0f,0.7627f,-0.101f,0f,1f,0f,3.5188f,-0.7627f,0f,-1.4969f,0.0309f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [0.7627f,0f,1.4969f,-0.0983f,0f,1f,0f,3.5188f,-1.4969f,0f,0.7627f,0.0313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-1.2438f,0f,3.828f,0f,0f,2.3958f,0f,0f,-3.828f,0f,-1.2438f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}