# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0f,0f,0.6736f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0f,0f,0.6736f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.0527f,0f,0.6538f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1667f,0f,0f,-0.8125f,0f,0.1496f,0f,0.6538f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1667f,0f,0f,0.8125f,0f,0.1496f,0f,0.6538f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body1) {transformation: [-1f,0f,0f,0f,0f,0.1282f,0f,0.5497f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0545f,0f,0f,-0.3687f,0f,0.5091f,0f,0.4375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0545f,0f,0f,0.3688f,0f,0.5091f,0f,0.4375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [-1.1873f,0f,1.6342f,-0.1021f,0f,1f,0f,0.9562f,-1.6342f,0f,-1.1873f,-0.0508f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-1.6342f,0f,-1.1873f,-0.1069f,0f,1f,0f,0.5062f,1.1873f,0f,-1.6342f,-0.0539f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-1.1873f,0f,1.6342f,-0.1025f,0f,1f,0f,0.5062f,-1.6342f,0f,-1.1873f,-0.0531f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-1.9951f,0f,0.316f,-0.104f,0f,1f,0f,0.5062f,-0.316f,0f,-1.9951f,-0.0522f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [0.316f,0f,1.9951f,-0.1008f,0f,1f,0f,0.5062f,-1.9951f,0f,0.316f,-0.0527f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-2.8446f,0f,3.9153f,0f,0f,2.3958f,0f,-3.0125f,-3.9153f,0f,-2.8446f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}