# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0f,0f,0.7248f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0f,0f,0.7248f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.0738f,0f,0.6971f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1667f,0f,0f,-0.8125f,0f,0.1795f,0f,0.6971f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1667f,0f,0f,0.8125f,0f,0.1795f,0f,0.6971f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body1) {transformation: [-1f,0f,0f,0f,0f,0.1538f,0f,0.5721f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0455f,0f,0f,-0.3687f,0f,0.5909f,0f,0.5f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0455f,0f,0f,0.3688f,0f,0.5909f,0f,0.5f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [-0.9942f,0f,1.9513f,-0.122f,0f,1f,0f,1.0375f,-1.9513f,0f,-0.9942f,-0.0629f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-1.9513f,0f,-0.9942f,-0.1265f,0f,1f,0f,0.5875f,0.9942f,0f,-1.9513f,-0.0669f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-0.9942f,0f,1.9513f,-0.1219f,0f,1f,0f,0.5875f,-1.9513f,0f,-0.9942f,-0.0654f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-2.0828f,0f,0.6767f,-0.1237f,0f,1f,0f,0.5875f,-0.6767f,0f,-2.0828f,-0.0647f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [0.6767f,0f,2.0828f,-0.1202f,0f,1f,0f,0.5875f,-2.0828f,0f,0.6767f,-0.0646f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-2.382f,0f,4.675f,0f,0f,2.3958f,0f,-2.9312f,-4.675f,0f,-2.382f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}