# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0f,0f,0.7773f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0f,0f,0.7773f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.0985f,0f,0.7404f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1667f,0f,0f,-0.8125f,0f,0.2094f,0f,0.7404f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1667f,0f,0f,0.8125f,0f,0.2094f,0f,0.7404f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body1) {transformation: [-1f,0f,0f,0f,0f,0.1795f,0f,0.5946f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0364f,0f,0f,-0.3687f,0f,0.6727f,0f,0.5625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0364f,0f,0f,0.3688f,0f,0.6727f,0f,0.5625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [-0.7293f,0f,2.2445f,-0.1403f,0f,1f,0f,1.1188f,-2.2445f,0f,-0.7293f,-0.0794f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-2.2445f,0f,-0.7293f,-0.1445f,0f,1f,0f,0.6687f,0.7293f,0f,-2.2445f,-0.0845f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-0.7293f,0f,2.2445f,-0.1398f,0f,1f,0f,0.6687f,-2.2445f,0f,-0.7293f,-0.0821f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-2.1028f,0f,1.0714f,-0.1419f,0f,1f,0f,0.6687f,-1.0714f,0f,-2.1028f,-0.0816f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [1.0714f,0f,2.1028f,-0.1381f,0f,1f,0f,0.6687f,-2.1028f,0f,1.0714f,-0.081f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-1.7472f,0f,5.3774f,0f,0f,2.3958f,0f,-2.85f,-5.3774f,0f,-1.7472f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}