# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(right_tendril) {transformation: [-1f,0f,0f,-0.5f,0f,0f,0f,0.8311f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_tendril) {transformation: [-1f,0f,0f,0.5f,0f,0f,0f,0.8311f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.1266f,0f,0.7837f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1667f,0f,0f,-0.8125f,0f,0.2393f,0f,0.7837f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1667f,0f,0f,0.8125f,0f,0.2393f,0f,0.7837f,0f,0f,-1.1667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body1) {transformation: [-1f,0f,0f,0f,0f,0.2051f,0f,0.617f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0273f,0f,0f,-0.3687f,0f,0.7545f,0f,0.625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0273f,0f,0f,0.3688f,0f,0.7545f,0f,0.625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hexadecagon) {transformation: [-0.3958f,0f,2.4989f,-0.1562f,0f,1f,0f,1.2f,-2.4989f,0f,-0.3958f,-0.1003f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line90) {transformation: [-2.4989f,0f,-0.3958f,-0.1598f,0f,1f,0f,0.75f,0.3958f,0f,-2.4989f,-0.1064f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line0) {transformation: [-0.3958f,0f,2.4989f,-0.1553f,0f,1f,0f,0.75f,-2.4989f,0f,-0.3958f,-0.103f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line1) {transformation: [-2.0468f,0f,1.4871f,-0.1575f,0f,1f,0f,0.75f,-1.4871f,0f,-2.0468f,-0.1029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line2) {transformation: [1.4871f,0f,2.0468f,-0.1536f,0f,1f,0f,0.75f,-2.0468f,0f,1.4871f,-0.1016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ring) {transformation: [-0.9482f,0f,5.9868f,0f,0f,2.3958f,0f,-2.7687f,-5.9868f,0f,-0.9482f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}