# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage warden:ancient_warden rig_hash set value 'b0b9ea65e9ea671bcad282600e17944691420582c20878dc40a31b81d3d517e6'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.death.frame dummy
scoreboard objectives add aj.spawn.frame dummy
scoreboard objectives add aj.shield_attack_start.frame dummy
scoreboard objectives add aj.walk.frame dummy