# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage warden:ancient_warden rig_hash set value 'f81562cdc264ec95a55c94b83d5369159f086b0dae19ad07bff86d9642595193'
scoreboard objectives add aj.ring_idle.frame dummy
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.death.frame dummy
scoreboard objectives add aj.spawn.frame dummy
scoreboard objectives add aj.shield_attack_start.frame dummy
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.shield_loop.frame dummy