name: Discord Custom Notification

on:
  push:
    branches: ["main" ]

jobs:
  discord-ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send Custom Message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          username: "GitHub"
          avatar_url: "https://cdn-icons-png.flaticon.com/512/25/25231.png"
          message: |
            <@&1538205057311445212> New updates on Git!
            
            📦 **Repo:** ${{ github.repository }}
            👤 **Author:** ${{ github.actor }}
            📝 **Commit:** ${{ github.event.head_commit.message }}
            🔗 ${{ github.event.head_commit.url }}
