name: Discord Commit Ping

on:
  push:
    branches: ["main" ]

jobs:
  discord-ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send Custom Message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          username: "GitHub"
          avatar_url: "https://images.icon-icons.com/3685/PNG/512/github_logo_icon_229278.png"
          message: |
            <@&1538205057311445212>
            🔗 ${{ github.event.head_commit.url }}
